<x-app-layout>
    <div class="mx-auto max-w-3xl"><h1 class="mb-6 text-3xl font-bold">{{ $managedUser->exists ? 'Modifier l’utilisateur' : 'Nouvel utilisateur' }}</h1>
        <form class="space-y-5 rounded-xl bg-white p-6 shadow-sm" method="POST" action="{{ $managedUser->exists ? route('users.update', $managedUser) : route('users.store') }}">@csrf @if($managedUser->exists) @method('PUT') @endif
            <div class="grid gap-5 sm:grid-cols-2"><label class="text-sm">Nom<input class="mt-1 w-full rounded-lg border-slate-300" name="name" value="{{ old('name', $managedUser->name) }}" required></label><label class="text-sm">E-mail<input type="email" class="mt-1 w-full rounded-lg border-slate-300" name="email" value="{{ old('email', $managedUser->email) }}" required></label><label class="text-sm">Mot de passe {{ $managedUser->exists ? '(laisser vide pour conserver)' : '' }}<input type="password" class="mt-1 w-full rounded-lg border-slate-300" name="password" @required(!$managedUser->exists)></label><label class="text-sm">Rôle<select class="mt-1 w-full rounded-lg border-slate-300" name="role_id" required>@foreach($roles as $role)<option value="{{ $role->id }}" @selected(old('role_id', $managedUser->role_id) == $role->id)>{{ $role->name }}</option>@endforeach</select></label><label class="text-sm">Agence<select class="mt-1 w-full rounded-lg border-slate-300" name="agency_id"><option value="">Toutes (Tenant Owner)</option>@foreach($agencies as $agency)<option value="{{ $agency->id }}" @selected(old('agency_id', $managedUser->agency_id) == $agency->id)>{{ $agency->name }}</option>@endforeach</select></label></div>
            <label class="flex items-center gap-2 text-sm"><input type="hidden" name="is_active" value="0"><input type="checkbox" name="is_active" value="1" @checked(old('is_active', $managedUser->is_active ?? true))> Compte actif</label>
            @if($errors->any())<div class="rounded-lg bg-red-50 p-3 text-sm text-red-800">{{ $errors->first() }}</div>@endif
            <button class="rounded-lg bg-slate-950 px-5 py-2 text-white">Enregistrer</button>
        </form>
    </div>
</x-app-layout>
