<x-app-layout><div class="mx-auto max-w-4xl space-y-6">
    <x-page-header :title="__('Demande de réservation')" :description="$booking->vehicle->registration_number"><x-slot:actions><a class="rf-button-secondary" href="{{ route('booking-admin.index') }}">{{ __('Retour aux demandes') }}</a></x-slot:actions></x-page-header><x-form-errors />
    <x-section-card :title="__('Coordonnées du demandeur')"><x-metadata-list><x-metadata-item :label="__('Nom')">{{ $booking->contact['first_name'] }} {{ $booking->contact['last_name'] }}</x-metadata-item><x-metadata-item :label="__('E-mail')">{{ $booking->contact['email'] ?? '—' }}</x-metadata-item><x-metadata-item :label="__('Téléphone')">{{ $booking->contact['phone'] ?? '—' }}</x-metadata-item><x-metadata-item :label="__('Message')">{{ $booking->contact['message'] ?? '—' }}</x-metadata-item><x-metadata-item :label="__('Période')">{{ App\Support\Ui\UiLabel::dateTime($booking->starts_at) }} → {{ App\Support\Ui\UiLabel::dateTime($booking->ends_at) }}</x-metadata-item><x-metadata-item :label="__('Devis présenté')">{{ App\Support\Ui\UiLabel::money($booking->quote_snapshot['total_amount'], $booking->quote_snapshot['currency']) }}</x-metadata-item></x-metadata-list></x-section-card>
    @if($booking->status === 'converted')<a class="rf-button-primary" href="{{ route('reservations.show', $booking->reservation_id) }}">{{ __('Ouvrir la réservation créée') }}</a>@elseif($booking->status === 'pending' && auth()->user()->hasPermission('reservation.create'))
        <x-section-card :title="__('Préparer un dossier')">
            <form method="GET" class="mb-5 flex items-end gap-3"><div class="grow"><x-input-label for="existing-search" :value="__('Rechercher un client existant par nom')" /><input id="existing-search" name="q" maxlength="80" value="{{ request('q') }}" class="mt-1 w-full"></div><x-secondary-button type="submit">{{ __('Rechercher') }}</x-secondary-button></form>
            <form method="POST" action="{{ route('booking-admin.convert', $booking) }}" class="space-y-4">@csrf<div><x-input-label for="booking-customer" :value="__('Client du dossier')" /><select id="booking-customer" name="customer_id" class="mt-1 w-full">@can('create', App\Models\Customer::class)<option value="">{{ __('Créer un client à vérifier avec les coordonnées reçues') }}</option>@endcan @foreach($customers as $customer)<option value="{{ $customer->id }}">{{ $customer->displayName() }}</option>@endforeach</select></div>
                <label class="flex items-start gap-3"><input type="checkbox" name="confirmed" value="1" required class="mt-1"><span>{{ __('J’ai vérifié le choix du client. Je préparerai les documents, le conducteur et le tarif avant de confirmer la réservation.') }}</span></label><x-primary-button>{{ __('Créer le brouillon') }}</x-primary-button>
            </form>
        </x-section-card>
        <x-section-card :title="__('Classer sans suite')"><form method="POST" action="{{ route('booking-admin.reject', $booking) }}" class="space-y-3">@csrf<div><x-input-label for="booking-reason" :value="__('Motif interne')" required /><textarea id="booking-reason" name="review_note" minlength="5" maxlength="1000" required rows="2" class="mt-1 w-full"></textarea></div><x-secondary-button type="submit">{{ __('Classer sans suite') }}</x-secondary-button></form></x-section-card>
    @else<x-flash-message type="info" :message="$booking->review_note ?? __('Demande consultable en lecture seule.')" />@endif
</div></x-app-layout>
