<x-app-layout><div class="mx-auto max-w-6xl space-y-6">
    <x-page-header :title="__('Catalogue de réservation public')" :description="__('Choisissez les informations et les véhicules que votre entreprise souhaite publier.')"><x-slot:actions>@if($profile?->enabled)<a class="rf-button-secondary" href="{{ route('booking.catalog', $profile->slug) }}" target="_blank" rel="noopener">{{ __('Ouvrir le catalogue') }}</a>@endif<a class="rf-button-secondary" href="{{ route('booking-admin.index') }}">{{ __('Demandes reçues') }}</a></x-slot:actions></x-page-header><x-form-errors />
    <x-section-card :title="__('Agence du catalogue')"><form method="GET" class="flex flex-wrap items-end gap-4"><div class="grow"><x-input-label for="catalog-agency" :value="__('Agence')" /><select id="catalog-agency" name="agency_id" class="mt-1 w-full">@foreach($agencies as $item)<option value="{{ $item->id }}" @selected($item->id === $agency->id)>{{ $item->name }}</option>@endforeach</select></div><x-secondary-button type="submit">{{ __('Afficher les véhicules') }}</x-secondary-button></form></x-section-card>
    <form method="POST" action="{{ route('booking-admin.settings.save') }}" class="space-y-6">@csrf<input type="hidden" name="agency_id" value="{{ $agency->id }}">
        <x-section-card :title="__('Informations publiques')">
            <div class="grid gap-4 sm:grid-cols-2"><div><x-input-label for="catalog-name" :value="__('Nom public')" required /><input id="catalog-name" name="public_name" required maxlength="120" value="{{ old('public_name', $profile?->public_name ?? auth()->user()->tenant->name) }}" class="mt-1 w-full"></div><div><x-input-label for="catalog-slug" :value="__('Adresse du catalogue')" required /><input id="catalog-slug" name="slug" required minlength="3" maxlength="60" pattern="[a-z0-9]+(-[a-z0-9]+)*" value="{{ old('slug', $profile?->slug) }}" placeholder="{{ __('mon-agence') }}" dir="ltr" class="mt-1 w-full"><p class="mt-1 text-xs text-slate-500">{{ url('/louer') }}/…</p><x-field-error :messages="$errors->get('slug')" /></div><div><x-input-label for="catalog-phone" :value="__('Téléphone public')" /><input id="catalog-phone" name="public_phone" maxlength="30" value="{{ old('public_phone', $profile?->public_phone) }}" class="mt-1 w-full"></div><div><x-input-label for="catalog-email" :value="__('E-mail public')" /><input id="catalog-email" name="public_email" type="email" maxlength="254" value="{{ old('public_email', $profile?->public_email) }}" class="mt-1 w-full"></div></div>
            <div class="mt-4"><x-input-label for="catalog-description" :value="__('Présentation publique')" /><textarea id="catalog-description" name="description" rows="3" maxlength="1500" class="mt-1 w-full">{{ old('description', $profile?->description) }}</textarea></div>
        </x-section-card>
        <x-section-card :title="__('Véhicules à publier')" :description="__('Le catalogue montre la marque, le modèle, la catégorie et le tarif demandé. Les plaques, dossiers clients et documents restent privés. Jusqu’à 500 véhicules actifs par agence.')">
            <div class="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">@forelse($vehicles as $vehicle)<label class="flex items-start gap-3 rounded-xl border p-3"><input type="checkbox" name="vehicles[]" value="{{ $vehicle->id }}" @checked(in_array($vehicle->id, old('vehicles', $published))) class="mt-1"><span><span class="block font-semibold">{{ $vehicle->brand }} {{ $vehicle->model }}</span><span class="text-sm text-slate-500">{{ $vehicle->registration_number }}</span></span></label>@empty<x-empty-state :title="__('Aucun véhicule actif dans cette agence')" />@endforelse</div>
        </x-section-card>
        <label class="flex items-start gap-3 rounded-xl border border-blue-200 bg-blue-50 p-4"><input type="checkbox" name="enabled" value="1" @checked(old('enabled', $profile?->enabled)) class="mt-1"><span>{{ __('Activer le catalogue public et publier les informations sélectionnées.') }}</span></label>
        <x-primary-button>{{ __('Enregistrer le catalogue') }}</x-primary-button>
    </form>
</div></x-app-layout>
