<x-app-layout><div class="mx-auto max-w-5xl space-y-6">
    <x-page-header :title="__('Coûts de possession').' — '.$vehicle->registration_number" :description="__('Hypothèses de gestion versionnées pour estimer la rentabilité du véhicule.')"><x-slot:actions><a class="rf-button-secondary" href="{{ route('vehicle-profitability.index') }}">{{ __('Voir la rentabilité') }}</a></x-slot:actions></x-page-header><x-form-errors />
    <x-section-card :title="__('Calcul des estimations')"><p class="text-sm leading-6 text-slate-600">{{ __('L’amortissement répartit le coût d’achat moins la valeur résiduelle sur la durée choisie. L’assurance est répartie par jour de l’année et les autres coûts par jour du mois. Les dépenses d’assurance déjà approuvées sont déduites du budget d’assurance pour éviter un double comptage. Ces estimations ne créent aucune écriture comptable.') }}</p></x-section-card>
    @if($canManage)
        <x-section-card :title="__('Enregistrer une nouvelle version')">
            <form method="POST" action="{{ route('vehicle-economics.store', $vehicle) }}" class="space-y-5">@csrf<input type="hidden" name="revision" value="{{ $profile?->revision ?? 0 }}">
                <div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
                    <div><x-input-label for="economic-from" :value="__('Applicable à partir du')" required /><input type="date" id="economic-from" name="effective_from" required value="{{ old('effective_from', $profile?->effective_from?->toDateString() ?? today()->toDateString()) }}" class="mt-1 w-full"><x-field-error :messages="$errors->get('effective_from')" /></div>
                    <div><x-input-label for="economic-acquired" :value="__('Date d’achat')" required /><input type="date" id="economic-acquired" name="acquired_on" required value="{{ old('acquired_on', $profile?->acquired_on?->toDateString()) }}" class="mt-1 w-full"></div>
                    <div><x-input-label for="economic-currency" :value="__('Devise')" required /><input id="economic-currency" name="currency" required maxlength="3" pattern="[A-Z]{3}" dir="ltr" value="{{ old('currency', $profile?->currency ?? auth()->user()->tenant->settings['currency'] ?? 'MAD') }}" class="mt-1 w-full"></div>
                    @foreach(['acquisition_cost' => 'Coût d’achat', 'residual_value' => 'Valeur résiduelle estimée', 'annual_insurance' => 'Budget annuel d’assurance', 'monthly_unrecorded_costs' => 'Autres coûts mensuels non saisis'] as $key => $label)
                        <div><x-input-label :for="'economic-'.$key" :value="__($label)" required /><input id="economic-{{ $key }}" name="{{ $key }}" inputmode="decimal" pattern="[0-9]{1,9}([.][0-9]{1,2})?" required value="{{ old($key, $profile?->$key ?? '0.00') }}" class="mt-1 w-full"><x-field-error :messages="$errors->get($key)" /></div>
                    @endforeach
                    <div><x-input-label for="economic-months" :value="__('Durée d’amortissement (mois)')" required /><input id="economic-months" name="depreciation_months" type="number" required min="1" max="240" value="{{ old('depreciation_months', $profile?->depreciation_months ?? 60) }}" class="mt-1 w-full"></div>
                </div>
                <div><x-input-label for="economic-expense" :value="__('Dépense d’achat déjà enregistrée (facultatif)')" /><select id="economic-expense" name="acquisition_expense_id" class="mt-1 w-full"><option value="">{{ __('Aucune dépense d’achat enregistrée') }}</option>@foreach($acquisitions as $expense)<option value="{{ $expense->id }}" @selected(old('acquisition_expense_id', $profile?->acquisition_expense_id) == $expense->id)>{{ $expense->expense_number }} · {{ App\Support\Ui\UiLabel::money($expense->amount, $expense->currency) }} · {{ App\Support\Ui\UiLabel::date($expense->expense_date) }}</option>@endforeach</select><p class="mt-1 text-sm text-slate-500">{{ __('Si l’achat figure déjà parmi les dépenses approuvées de type Autre, associez-le ici. Il restera visible dans les dépenses réelles et sera remplacé par l’amortissement dans la marge estimée.') }}</p></div>
                <div><x-input-label for="economic-reason" :value="__('Motif de cette version')" required /><textarea id="economic-reason" name="reason" required minlength="5" maxlength="500" rows="2" class="mt-1 w-full">{{ old('reason') }}</textarea></div>
                <label class="flex items-start gap-3"><input name="no_duplicate_costs" type="checkbox" value="1" required class="mt-1"><span>{{ __('Les autres coûts mensuels ne sont pas déjà saisis dans les dépenses. J’ai associé la dépense d’achat si elle existe.') }}</span></label>
                <x-primary-button>{{ __('Enregistrer les hypothèses') }}</x-primary-button>
            </form>
        </x-section-card>
    @endif
    <x-section-card :title="__('Historique des hypothèses')"><div class="space-y-4">@forelse($profiles as $version)<article class="rounded-xl border p-4"><h2 class="font-semibold">{{ __('Version') }} {{ $version->revision }} · {{ App\Support\Ui\UiLabel::date($version->effective_from) }}</h2><p class="mt-2 text-sm">{{ __('Coût d’achat') }} : {{ App\Support\Ui\UiLabel::money($version->acquisition_cost, $version->currency) }} · {{ __('Valeur résiduelle') }} : {{ App\Support\Ui\UiLabel::money($version->residual_value, $version->currency) }}</p><p class="mt-2 text-sm">{{ $version->reason }}</p></article>@empty<x-empty-state :title="__('Aucune hypothèse de coût enregistrée')" />@endforelse</div><div class="mt-4">{{ $profiles->links() }}</div></x-section-card>
</div></x-app-layout>
