<x-app-layout>
    <div class="mx-auto max-w-6xl space-y-6">
        <div><a href="{{ route('insurance.index') }}" class="text-sm text-indigo-700">{{ __('← Assurance') }}</a><div class="mt-2 flex flex-wrap items-center justify-between gap-3"><h1 class="text-3xl font-bold">{{ $claim->claim_number }}</h1><x-status-badge :value="$claim->status" /></div><p class="mt-2 text-sm text-slate-600">{{ __('Aucune responsabilité juridique n’est déterminée automatiquement.') }}</p></div>
        <x-form-errors />
        <section class="rounded-xl bg-white p-5 shadow-sm"><dl class="grid gap-4 text-sm md:grid-cols-3"><div><dt class="text-slate-500">{{ __('Police') }}</dt><dd><a class="underline" href="{{ route('insurance.policies.show',$claim->policy) }}">{{ $claim->policy->maskedPolicyNumber() }}</a></dd></div><div><dt class="text-slate-500">{{ __('Véhicule') }}</dt><dd>{{ $claim->policy->vehicle->registration_number }}</dd></div><div><dt class="text-slate-500">{{ __('Incident') }}</dt><dd>{{ App\Support\Ui\UiLabel::dateTime($claim->incident_at) }}</dd></div><div><dt class="text-slate-500">{{ __('Déclaration') }}</dt><dd>{{ App\Support\Ui\UiLabel::dateTime($claim->reported_at) }}</dd></div><div><dt class="text-slate-500">{{ __('Demandé') }}</dt><dd>{{ App\Support\Ui\UiLabel::money($claim->claimed_amount,$claim->policy->currency) }}</dd></div><div><dt class="text-slate-500">{{ __('Approuvé humainement') }}</dt><dd>{{ App\Support\Ui\UiLabel::money($claim->approved_amount,$claim->policy->currency) }}</dd></div><div><dt class="text-slate-500">{{ __('Réglé') }}</dt><dd>{{ App\Support\Ui\UiLabel::money($claim->settled_amount,$claim->policy->currency) }}</dd></div>@if($claim->rentalContract)<div><dt class="text-slate-500">{{ __('Contrat') }}</dt><dd><a class="underline" href="{{ route('contracts.show',$claim->rentalContract) }}">{{ $claim->rentalContract->contract_number }}</a></dd></div>@endif @if($claim->damageReport)<div><dt class="text-slate-500">{{ __('Dommage') }}</dt><dd>{{ $claim->damageReport->damage_number }}</dd></div>@endif</dl></section>

        @can('manage',$claim)<section class="rounded-xl bg-white p-5 shadow-sm"><h2 class="font-semibold">{{ __('Transition humaine autorisée') }}</h2><div class="mt-4 space-y-4">
            @if($claim->status->value === 'reported')
                <form method="POST" action="{{ route('insurance.claims.submit',$claim) }}" class="space-y-2">@csrf<x-input-label for="claim-submit-note" :value="__('Note de soumission')" /><input id="claim-submit-note" name="note" value="{{ old('note') }}" aria-describedby="claim-submit-note-error" class="w-full rounded border-slate-300"><x-field-error id="claim-submit-note-error" :messages="$errors->get('note')" /><button class="rounded bg-slate-900 px-4 py-2 text-white">{{ __('Soumettre') }}</button></form>
                <form method="POST" action="{{ route('insurance.claims.review',$claim) }}" class="space-y-2">@csrf<x-input-label for="claim-direct-review-note" :value="__('Motif de revue')" /><input id="claim-direct-review-note" name="note" value="{{ old('note') }}" aria-describedby="claim-direct-review-note-error" class="w-full rounded border-slate-300"><x-field-error id="claim-direct-review-note-error" :messages="$errors->get('note')" /><button class="rounded border px-4 py-2">{{ __('Démarrer directement la revue') }}</button></form>
            @elseif($claim->status->value === 'submitted')
                <form method="POST" action="{{ route('insurance.claims.review',$claim) }}" class="space-y-2">@csrf<x-input-label for="claim-review-note" :value="__('Motif de revue')" /><input id="claim-review-note" name="note" value="{{ old('note') }}" aria-describedby="claim-review-note-error" class="w-full rounded border-slate-300"><x-field-error id="claim-review-note-error" :messages="$errors->get('note')" /><button class="rounded bg-slate-900 px-4 py-2 text-white">{{ __('Démarrer la revue') }}</button></form>
            @elseif($claim->status->value === 'under_review')
                <form method="POST" action="{{ route('insurance.claims.approve',$claim) }}" class="grid gap-3 md:grid-cols-2" x-belkhir-space-confirm data-confirm-title="{{ __('Approuver le sinistre') }}" data-confirm-resource="{{ __('Sinistre sélectionné') }}" data-confirm-consequence="{{ __('Cette décision humaine et le montant approuvé seront enregistrés dans l’historique du sinistre.') }}" data-confirm-label="{{ __('Approuver') }}">@csrf<div><x-input-label for="claim-approved-amount" :value="__('Montant approuvé (').$claim->policy->currency.')'" required /><input id="claim-approved-amount" name="approved_amount" required inputmode="decimal" value="{{ old('approved_amount') }}" aria-describedby="claim-approved-amount-error" class="mt-1 w-full rounded border-slate-300"><x-field-error id="claim-approved-amount-error" :messages="$errors->get('approved_amount')" /></div><div><x-input-label for="claim-approval-note" :value="__('Justification humaine')" /><input id="claim-approval-note" name="note" value="{{ old('note') }}" aria-describedby="claim-approval-note-error" class="mt-1 w-full rounded border-slate-300"><x-field-error id="claim-approval-note-error" :messages="$errors->get('note')" /></div><button class="rounded bg-emerald-700 px-4 py-2 text-white md:col-span-2">{{ __('Approuver') }}</button></form>
                <form method="POST" action="{{ route('insurance.claims.reject',$claim) }}" class="space-y-2" x-belkhir-space-confirm data-confirm-title="{{ __('Rejeter le sinistre') }}" data-confirm-resource="{{ __('Sinistre sélectionné') }}" data-confirm-consequence="{{ __('Le sinistre sera rejeté et le motif saisi sera conservé dans son historique.') }}" data-confirm-label="{{ __('Rejeter') }}">@csrf<x-input-label for="claim-rejection-note" :value="__('Motif du rejet')" required /><input id="claim-rejection-note" name="note" required value="{{ old('note') }}" aria-describedby="claim-rejection-note-error" class="w-full rounded border-slate-300"><x-field-error id="claim-rejection-note-error" :messages="$errors->get('note')" /><button class="rounded bg-red-700 px-4 py-2 text-white">{{ __('Rejeter') }}</button></form>
            @elseif($claim->status->value === 'approved')
                <form method="POST" action="{{ route('insurance.claims.settle',$claim) }}" class="grid gap-3 md:grid-cols-2" x-belkhir-space-confirm data-confirm-title="{{ __('Enregistrer le règlement') }}" data-confirm-resource="{{ __('Sinistre sélectionné') }}" data-confirm-consequence="{{ __('Le montant réglé sera enregistré dans l’historique du sinistre.') }}" data-confirm-label="{{ __('Enregistrer le règlement') }}">@csrf<div><x-input-label for="claim-settled-amount" :value="__('Montant réglé (').$claim->policy->currency.')'" required /><input id="claim-settled-amount" name="settled_amount" required inputmode="decimal" value="{{ old('settled_amount') }}" aria-describedby="claim-settled-amount-error" class="mt-1 w-full rounded border-slate-300"><x-field-error id="claim-settled-amount-error" :messages="$errors->get('settled_amount')" /></div><div><x-input-label for="claim-settlement-note" :value="__('Note de règlement')" /><input id="claim-settlement-note" name="note" value="{{ old('note') }}" aria-describedby="claim-settlement-note-error" class="mt-1 w-full rounded border-slate-300"><x-field-error id="claim-settlement-note-error" :messages="$errors->get('note')" /></div><button class="inline-flex items-center justify-center gap-2 rounded bg-emerald-700 px-4 py-2 text-white md:col-span-2"><x-icon name="save" size="xs" />{{ __('Enregistrer le règlement') }}</button></form>
            @elseif($claim->status->value === 'settled')
                <form method="POST" action="{{ route('insurance.claims.close',$claim) }}" class="space-y-2" x-belkhir-space-confirm data-confirm-title="{{ __('Clôturer le sinistre') }}" data-confirm-resource="{{ __('Sinistre sélectionné') }}" data-confirm-consequence="{{ __('Le sinistre sera clôturé après les contrôles existants de la preuve de règlement.') }}" data-confirm-label="{{ __('Clôturer') }}">@csrf<x-input-label for="claim-closing-note" :value="__('Note de clôture')" /><input id="claim-closing-note" name="note" value="{{ old('note') }}" aria-describedby="claim-closing-note-error" class="w-full rounded border-slate-300"><x-field-error id="claim-closing-note-error" :messages="$errors->get('note')" /><button class="rounded bg-slate-900 px-4 py-2 text-white">{{ __('Clôturer') }}</button></form>
            @else<p class="text-sm text-slate-500">{{ __('Aucune transition disponible.') }}</p>@endif
        </div></section>@endcan

        <section class="rounded-xl bg-white p-5 shadow-sm"><h2 class="font-semibold">{{ __('Documents privés du sinistre') }}</h2><div class="mt-4 grid gap-3 sm:grid-cols-2">@forelse($claim->documents as $document)@can('view',$document)<a href="{{ route('documents.show',$document) }}" class="rounded border p-3 text-sm"><strong>{{ $document->title }}</strong><p class="text-slate-500">{{ App\Support\Ui\UiLabel::get($document->document_type) }} {{ __('· version') }} {{ $document->currentVersion?->version_number ?? '—' }}</p></a>@endcan @empty<x-empty-state :title="__('Aucun document privé')" />@endforelse</div>@can('uploadDocument',$claim)<form method="POST" enctype="multipart/form-data" action="{{ route('insurance.claims.documents.store',$claim) }}" class="mt-5 grid gap-3 border-t pt-5 sm:grid-cols-2" data-loading-form>@csrf<input type="hidden" name="is_sensitive" value="1"><label class="text-sm">{{ __('Type') }}<select name="document_type" class="mt-1 w-full rounded border-slate-300">@foreach($documentTypes as $type)<option value="{{ $type->value }}">{{ App\Support\Ui\UiLabel::get($type) }}</option>@endforeach</select></label><label class="text-sm">{{ __('Titre') }}<input name="title" required class="mt-1 w-full rounded border-slate-300"></label><x-file-input id="claim-document-file" name="file" :label="__('Fichier privé')" required :errors="$errors->get('file')" /><label class="text-sm">{{ __('Conservation jusqu’au') }}<input type="date" name="retention_until" class="mt-1 w-full rounded border-slate-300"></label><div class="sm:col-span-2"><x-submit-button :label="__('Ajouter le document')" loading-label="{{ __('Ajout en cours…') }}" /></div></form>@endcan</section>
        <section class="rounded-xl bg-white p-5 shadow-sm"><h2 class="font-semibold">{{ __('Historique du sinistre') }}</h2><ol class="mt-4 space-y-3 text-sm">@forelse($claim->statusHistories->sortByDesc(fn($h)=>[$h->changed_at,$h->id]) as $history)<li class="border-l-2 border-slate-300 ps-3"><strong>{{ $history->from_status?->label() ?? __('Création') }} → {{ $history->to_status->label() }}</strong><span class="ms-2 text-slate-500">{{ App\Support\Ui\UiLabel::dateTime($history->changed_at) }}</span>@if($history->actor)<p class="text-slate-500">{{ __('Par') }} {{ $history->actor->name }}</p>@endif @if($history->note)<p>{{ $history->note }}</p>@endif</li>@empty<x-empty-state :title="__('Aucun historique')" />@endforelse</ol></section>
    </div>
</x-app-layout>
