<x-app-layout>
    <div class="mx-auto max-w-6xl space-y-6">
        <div><a href="{{ route('insurance.index') }}" class="text-sm text-indigo-700">← Assurance</a><div class="mt-2 flex flex-wrap items-center justify-between gap-3"><h1 class="text-3xl font-bold">{{ $claim->claim_number }}</h1><x-status-badge :value="$claim->status" /></div><p class="mt-2 text-sm text-slate-600">Aucune responsabilité juridique n’est déterminée automatiquement.</p></div>
        <x-form-errors />
        <section class="rounded-xl bg-white p-5 shadow-sm"><dl class="grid gap-4 text-sm md:grid-cols-3"><div><dt class="text-slate-500">Police</dt><dd><a class="underline" href="{{ route('insurance.policies.show',$claim->policy) }}">{{ $claim->policy->maskedPolicyNumber() }}</a></dd></div><div><dt class="text-slate-500">Véhicule</dt><dd>{{ $claim->policy->vehicle->registration_number }}</dd></div><div><dt class="text-slate-500">Incident</dt><dd>{{ App\Support\Ui\UiLabel::dateTime($claim->incident_at) }}</dd></div><div><dt class="text-slate-500">Déclaration</dt><dd>{{ App\Support\Ui\UiLabel::dateTime($claim->reported_at) }}</dd></div><div><dt class="text-slate-500">Demandé</dt><dd>{{ App\Support\Ui\UiLabel::money($claim->claimed_amount,$claim->policy->currency) }}</dd></div><div><dt class="text-slate-500">Approuvé humainement</dt><dd>{{ App\Support\Ui\UiLabel::money($claim->approved_amount,$claim->policy->currency) }}</dd></div><div><dt class="text-slate-500">Réglé</dt><dd>{{ App\Support\Ui\UiLabel::money($claim->settled_amount,$claim->policy->currency) }}</dd></div>@if($claim->rentalContract)<div><dt class="text-slate-500">Contrat</dt><dd><a class="underline" href="{{ route('contracts.show',$claim->rentalContract) }}">{{ $claim->rentalContract->contract_number }}</a></dd></div>@endif @if($claim->damageReport)<div><dt class="text-slate-500">Dommage</dt><dd>{{ $claim->damageReport->damage_number }}</dd></div>@endif</dl></section>

        @can('manage',$claim)<section class="rounded-xl bg-white p-5 shadow-sm"><h2 class="font-semibold">Transition humaine autorisée</h2><div class="mt-4 space-y-4">
            @if($claim->status->value === 'reported')<form method="POST" action="{{ route('insurance.claims.submit',$claim) }}" class="flex flex-wrap gap-2">@csrf<input name="note" value="{{ old('note') }}" placeholder="Note facultative" class="rounded border-slate-300"><button class="rounded bg-slate-900 px-4 py-2 text-white">Soumettre</button></form><form method="POST" action="{{ route('insurance.claims.review',$claim) }}" class="flex flex-wrap gap-2">@csrf<input name="note" value="{{ old('note') }}" placeholder="Motif de revue" class="rounded border-slate-300"><button class="rounded border px-4 py-2">Démarrer directement la revue</button></form>
            @elseif($claim->status->value === 'submitted')<form method="POST" action="{{ route('insurance.claims.review',$claim) }}" class="flex flex-wrap gap-2">@csrf<input name="note" value="{{ old('note') }}" placeholder="Motif de revue" class="rounded border-slate-300"><button class="rounded bg-slate-900 px-4 py-2 text-white">Démarrer la revue</button></form>
            @elseif($claim->status->value === 'under_review')<form method="POST" action="{{ route('insurance.claims.approve',$claim) }}" class="grid gap-2 md:grid-cols-3" onsubmit="return confirm('Confirmer cette décision humaine ?')">@csrf<input name="approved_amount" required value="{{ old('approved_amount') }}" placeholder="Montant approuvé" class="rounded border-slate-300"><input name="note" value="{{ old('note') }}" placeholder="Justification" class="rounded border-slate-300"><button class="rounded bg-emerald-700 px-4 py-2 text-white">Approuver</button></form><form method="POST" action="{{ route('insurance.claims.reject',$claim) }}" class="flex flex-wrap gap-2" onsubmit="return confirm('Rejeter ce sinistre ?')">@csrf<input name="note" required value="{{ old('note') }}" placeholder="Motif du rejet" class="rounded border-slate-300"><button class="rounded bg-red-700 px-4 py-2 text-white">Rejeter</button></form>
            @elseif($claim->status->value === 'approved')<form method="POST" action="{{ route('insurance.claims.settle',$claim) }}" class="grid gap-2 md:grid-cols-3" onsubmit="return confirm('Enregistrer ce règlement ?')">@csrf<input name="settled_amount" required value="{{ old('settled_amount') }}" placeholder="Montant réglé" class="rounded border-slate-300"><input name="note" value="{{ old('note') }}" placeholder="Note" class="rounded border-slate-300"><button class="rounded bg-emerald-700 px-4 py-2 text-white">Enregistrer le règlement</button></form>
            @elseif($claim->status->value === 'settled')<form method="POST" action="{{ route('insurance.claims.close',$claim) }}" class="flex flex-wrap gap-2" onsubmit="return confirm('Clôturer ce sinistre après contrôle de la preuve de règlement ?')">@csrf<input name="note" value="{{ old('note') }}" placeholder="Note de clôture" class="rounded border-slate-300"><button class="rounded bg-slate-900 px-4 py-2 text-white">Clôturer</button></form>
            @else<p class="text-sm text-slate-500">Aucune transition disponible.</p>@endif
        </div></section>@endcan

        <section class="rounded-xl bg-white p-5 shadow-sm"><h2 class="font-semibold">Documents privés du sinistre</h2><div class="mt-4 grid gap-3 sm:grid-cols-2">@forelse($claim->documents as $document)@can('view',$document)<a href="{{ route('documents.show',$document) }}" class="rounded border p-3 text-sm"><strong>{{ $document->title }}</strong><p class="text-slate-500">{{ App\Support\Ui\UiLabel::get($document->document_type) }} · version {{ $document->currentVersion?->version_number ?? '—' }}</p></a>@endcan @empty<x-empty-state title="Aucun document privé" />@endforelse</div>@can('uploadDocument',$claim)<form method="POST" enctype="multipart/form-data" action="{{ route('insurance.claims.documents.store',$claim) }}" class="mt-5 grid gap-3 border-t pt-5 sm:grid-cols-2">@csrf<input type="hidden" name="is_sensitive" value="1"><label class="text-sm">Type<select name="document_type" class="mt-1 w-full rounded border-slate-300">@foreach($documentTypes as $type)<option value="{{ $type->value }}">{{ App\Support\Ui\UiLabel::get($type) }}</option>@endforeach</select></label><label class="text-sm">Titre<input name="title" required class="mt-1 w-full rounded border-slate-300"></label><label class="text-sm">Fichier privé<input type="file" name="file" required class="mt-1 block w-full"></label><label class="text-sm">Conservation jusqu’au<input type="date" name="retention_until" class="mt-1 w-full rounded border-slate-300"></label><div class="sm:col-span-2"><button class="rounded bg-slate-900 px-4 py-2 text-white">Ajouter le document</button></div></form>@endcan</section>
        <section class="rounded-xl bg-white p-5 shadow-sm"><h2 class="font-semibold">Chronologie immuable</h2><ol class="mt-4 space-y-3 text-sm">@forelse($claim->statusHistories->sortByDesc(fn($h)=>[$h->changed_at,$h->id]) as $history)<li class="border-l-2 border-slate-300 pl-3"><strong>{{ $history->from_status?->label() ?? 'Création' }} → {{ $history->to_status->label() }}</strong><span class="ml-2 text-slate-500">{{ App\Support\Ui\UiLabel::dateTime($history->changed_at) }}</span>@if($history->actor)<p class="text-slate-500">Par {{ $history->actor->name }}</p>@endif @if($history->note)<p>{{ $history->note }}</p>@endif</li>@empty<x-empty-state title="Aucun historique" />@endforelse</ol></section>
    </div>
</x-app-layout>
