<x-app-layout>
    <div class="space-y-8">
        <div><p class="text-sm text-slate-500">Registres opérationnels</p><h1 class="text-3xl font-bold">Finance et clôture</h1><p class="mt-2 text-sm text-slate-600">Aucune comptabilité générale, passerelle bancaire ou donnée de carte.</p></div>
        @if($errors->any())<div class="rounded-lg bg-red-50 p-4 text-sm text-red-800">{{ $errors->first() }}</div>@endif

        <section class="rounded-xl bg-white p-6 shadow-sm"><h2 class="text-lg font-semibold">Factures</h2><div class="mt-4 overflow-x-auto"><table class="min-w-full text-sm"><thead><tr class="text-left text-slate-500"><th class="py-2">Numéro</th><th>Contrat</th><th>Statut</th><th>Total</th><th>Payé</th><th>Solde</th></tr></thead><tbody>
            @forelse($invoices as $invoice)<tr class="border-t"><td class="py-3"><a class="font-medium text-indigo-700" href="{{ route('finance.invoices.show', $invoice) }}">{{ $invoice->invoice_number }}</a></td><td><a class="underline" href="{{ route('contracts.show', $invoice->rentalContract) }}">{{ $invoice->rentalContract->contract_number }}</a></td><td><span class="rounded-full bg-slate-100 px-2 py-1 text-xs">{{ $invoice->status }}</span></td><td>{{ $invoice->total_amount }} {{ $invoice->currency }}</td><td>{{ $invoice->paid_amount }} {{ $invoice->currency }}</td><td>{{ $invoice->balance_due }} {{ $invoice->currency }}</td></tr>
            @empty<tr><td colspan="6" class="py-8 text-slate-500">Aucune facture. La création démarre depuis un contrat retourné.</td></tr>@endforelse
        </tbody></table></div><div class="mt-4">{{ $invoices->links() }}</div></section>

        <div class="grid gap-6 lg:grid-cols-2">
            <section class="rounded-xl bg-white p-6 shadow-sm"><h2 class="font-semibold">Paiements récents</h2><div class="mt-4 space-y-3 text-sm">@forelse($payments as $payment)<div class="border-b pb-3"><p class="font-medium">{{ $payment->payment_number }} · {{ $payment->amount }} {{ $payment->currency }}</p><p class="text-slate-500">{{ $payment->status }} · {{ $payment->payment_method }}@if($payment->rentalContract) · <a class="underline" href="{{ route('contracts.show', $payment->rentalContract) }}">{{ $payment->rentalContract->contract_number }}</a>@endif</p>@foreach($payment->allocations as $allocation)<a class="text-xs text-indigo-700 underline" href="{{ route('finance.invoices.show', $allocation->invoice) }}">Alloué à {{ $allocation->invoice->invoice_number }}</a>@endforeach</div>@empty<p class="text-slate-500">Aucun paiement.</p>@endforelse</div></section>
            <section class="rounded-xl bg-white p-6 shadow-sm"><h2 class="font-semibold">Cautions</h2><div class="mt-4 space-y-3 text-sm">@forelse($deposits as $entry)<div class="border-b pb-3"><p class="font-medium">{{ $entry->transaction_number }} · {{ $entry->amount }} {{ $entry->currency }}</p><p class="text-slate-500">{{ $entry->transaction_type }} · <a class="underline" href="{{ route('contracts.show', $entry->rentalContract) }}">{{ $entry->rentalContract->contract_number }}</a></p></div>@empty<p class="text-slate-500">Aucun mouvement.</p>@endforelse</div></section>
        </div>

        @if(auth()->user()->hasPermission('expense.create'))
            <section class="rounded-xl bg-white p-6 shadow-sm"><h2 class="font-semibold">Créer une dépense</h2><form method="POST" action="{{ route('finance.expenses.store') }}" class="mt-4 grid gap-3 md:grid-cols-3">@csrf
                <label class="text-sm">Agence<select name="agency_id" required class="mt-1 w-full rounded border-slate-300"><option value="">Choisir</option>@foreach($agencies as $agency)<option value="{{ $agency->id }}" @selected(old('agency_id') == $agency->id)>{{ $agency->name }}</option>@endforeach</select><x-input-error :messages="$errors->get('agency_id')" /></label>
                <label class="text-sm">Catégorie<select name="category" class="mt-1 w-full rounded border-slate-300">@foreach(['maintenance','insurance','fuel','cleaning','administration','other'] as $category)<option value="{{ $category }}" @selected(old('category') === $category)>{{ $category }}</option>@endforeach</select></label>
                <label class="text-sm">Date<input type="date" name="expense_date" required value="{{ old('expense_date', now()->toDateString()) }}" class="mt-1 w-full rounded border-slate-300"></label>
                <label class="text-sm">Véhicule facultatif<select name="vehicle_id" class="mt-1 w-full rounded border-slate-300"><option value="">Aucun</option>@foreach($vehicles as $vehicle)<option value="{{ $vehicle->id }}" @selected(old('vehicle_id') == $vehicle->id)>{{ $vehicle->registration_number }}</option>@endforeach</select></label>
                <label class="text-sm">Contrat facultatif<select name="rental_contract_id" class="mt-1 w-full rounded border-slate-300"><option value="">Aucun</option>@foreach($contracts as $contract)<option value="{{ $contract->id }}" @selected(old('rental_contract_id') == $contract->id)>{{ $contract->contract_number }}</option>@endforeach</select></label>
                <label class="text-sm">Fournisseur<input name="supplier" value="{{ old('supplier') }}" class="mt-1 w-full rounded border-slate-300"></label>
                <label class="text-sm md:col-span-2">Description<input name="description" required value="{{ old('description') }}" class="mt-1 w-full rounded border-slate-300"><x-input-error :messages="$errors->get('description')" /></label>
                <label class="text-sm">Montant (MAD)<input name="amount" inputmode="decimal" required value="{{ old('amount') }}" class="mt-1 w-full rounded border-slate-300"><x-input-error :messages="$errors->get('amount')" /></label>
                <label class="text-sm">Taxe indicative (MAD)<input name="tax_amount" inputmode="decimal" value="{{ old('tax_amount', '0.00') }}" class="mt-1 w-full rounded border-slate-300"></label><input type="hidden" name="currency" value="MAD">
                <div class="self-end"><button class="rounded bg-slate-900 px-4 py-2 text-white">Enregistrer le brouillon</button></div>
            </form></section>
        @endif

        <section class="rounded-xl bg-white p-6 shadow-sm"><h2 class="font-semibold">Dépenses</h2><div class="mt-4 overflow-x-auto"><table class="min-w-full text-sm"><thead><tr class="text-left text-slate-500"><th class="py-2">Numéro</th><th>Catégorie</th><th>Montant</th><th>Référence</th><th>Statut</th><th></th></tr></thead><tbody>@forelse($expenses as $expense)<tr class="border-t"><td class="py-3">{{ $expense->expense_number }}</td><td>{{ $expense->category }}</td><td>{{ $expense->amount }} {{ $expense->currency }}</td><td>{{ $expense->maintenanceOrder?->maintenance_number ?? $expense->rentalContract?->contract_number ?? $expense->vehicle?->registration_number ?? '—' }}</td><td>{{ $expense->status }}</td><td>@if($expense->status === 'draft' && auth()->user()->hasPermission('expense.approve'))<form method="POST" action="{{ route('finance.expenses.approve', $expense) }}" onsubmit="return confirm('Approuver cette dépense ?')">@csrf<button class="text-indigo-700 underline">Approuver</button></form>@endif</td></tr>@empty<tr><td colspan="6" class="py-8 text-slate-500">Aucune dépense.</td></tr>@endforelse</tbody></table></div></section>
    </div>
</x-app-layout>
