<x-app-layout>
    <div class="mx-auto max-w-6xl space-y-6">
        <div class="flex flex-wrap items-start justify-between gap-3"><div><a href="{{ route('finance.index') }}" class="text-sm text-indigo-700">← Finance</a><p class="mt-2 text-sm text-slate-500">Facture</p><h1 class="text-3xl font-bold">{{ $invoice->invoice_number }}</h1><a href="{{ route('contracts.show', $invoice->rentalContract) }}" class="text-sm underline">Contrat {{ $invoice->rentalContract->contract_number }}</a></div><span class="rounded-full bg-slate-200 px-3 py-1 text-sm font-semibold">{{ $invoice->status }}</span></div>
        @if($errors->any())<div class="rounded-lg bg-red-50 p-4 text-sm text-red-800">{{ $errors->first() }}</div>@endif

        <section class="rounded-xl bg-white p-6 shadow-sm"><div class="rounded-lg bg-slate-50 p-4 text-sm"><p class="font-medium">{{ $invoice->customer_snapshot['name'] ?? 'Client' }}</p><p>{{ $invoice->customer_snapshot['city'] ?? '' }}</p></div><div class="mt-6 overflow-x-auto"><table class="min-w-full text-sm"><thead><tr class="border-b text-left text-slate-500"><th class="py-3">Description</th><th>HT</th><th>Taxe</th><th>Total</th></tr></thead><tbody>@foreach($invoice->lines as $line)<tr class="border-b"><td class="py-3">{{ $line->description }}</td><td>{{ $line->subtotal }} {{ $invoice->currency }}</td><td>{{ $line->tax_amount }} {{ $invoice->currency }}</td><td>{{ $line->total_amount }} {{ $invoice->currency }}</td></tr>@endforeach</tbody></table></div><div class="mt-6 ml-auto max-w-xs space-y-2 text-sm"><p class="flex justify-between"><span>Sous-total</span><strong>{{ $invoice->subtotal }} {{ $invoice->currency }}</strong></p><p class="flex justify-between"><span>Taxe</span><strong>{{ $invoice->tax_amount }} {{ $invoice->currency }}</strong></p><p class="flex justify-between text-lg"><span>Total</span><strong>{{ $invoice->total_amount }} {{ $invoice->currency }}</strong></p><p class="flex justify-between"><span>Payé</span><strong>{{ $invoice->paid_amount }} {{ $invoice->currency }}</strong></p><p class="flex justify-between"><span>Solde</span><strong>{{ $invoice->balance_due }} {{ $invoice->currency }}</strong></p></div></section>

        <section class="rounded-xl bg-white p-5 shadow-sm"><h2 class="font-semibold">Actions facture</h2><div class="mt-4 flex flex-wrap gap-3">
            @if($invoice->status === 'draft' && auth()->user()->hasPermission('invoice.issue'))<form method="POST" action="{{ route('finance.invoices.issue', $invoice) }}" class="flex gap-2" onsubmit="return confirm('Émettre et figer cette facture ?')">@csrf<input type="date" name="due_at" class="rounded border-slate-300"><button class="rounded bg-slate-900 px-4 py-2 text-white">Émettre</button></form>@endif
            @if($invoice->status === 'issued' && $invoice->paid_amount === '0.00' && auth()->user()->hasPermission('invoice.void'))<form method="POST" action="{{ route('finance.invoices.void', $invoice) }}" class="flex gap-2" onsubmit="return confirm('Annuler cette facture sans la supprimer ?')">@csrf<input name="reason" required placeholder="Motif obligatoire" class="rounded border-slate-300"><button class="rounded border border-red-300 px-4 py-2 text-red-700">Annuler</button></form>@endif
        </div></section>

        @if(in_array($invoice->status, ['issued','partially_paid']) && auth()->user()->hasPermission('payment.create'))
            @php($paymentKey = old('idempotency_key', 'web-pay-'.Illuminate\Support\Str::uuid()))
            <section class="rounded-xl bg-white p-5 shadow-sm"><h2 class="font-semibold">Enregistrer un paiement</h2><p class="mt-1 text-xs text-slate-500">Opération manuelle uniquement; aucune donnée de carte n’est collectée.</p><form method="POST" action="{{ route('finance.payments.store') }}" class="mt-4 grid gap-3 md:grid-cols-3">@csrf
                <input type="hidden" name="agency_id" value="{{ $invoice->agency_id }}"><input type="hidden" name="rental_contract_id" value="{{ $invoice->rental_contract_id }}"><input type="hidden" name="customer_id" value="{{ $invoice->customer_id }}"><input type="hidden" name="currency" value="{{ $invoice->currency }}"><input type="hidden" name="idempotency_key" value="{{ $paymentKey }}">
                <label class="text-sm">Montant ({{ $invoice->currency }})<input name="amount" inputmode="decimal" required value="{{ old('amount', $invoice->balance_due) }}" class="mt-1 w-full rounded border-slate-300"><x-input-error :messages="$errors->get('amount')" /></label>
                <label class="text-sm">Mode<select name="payment_method" class="mt-1 w-full rounded border-slate-300"><option value="cash">Espèces</option><option value="bank_transfer">Virement</option><option value="cheque">Chèque</option><option value="card">Carte — référence externe seulement</option><option value="other">Autre</option></select></label>
                <label class="text-sm">Référence externe<input name="external_reference" value="{{ old('external_reference') }}" class="mt-1 w-full rounded border-slate-300"></label>
                <label class="text-sm md:col-span-2">Notes<input name="notes" value="{{ old('notes') }}" class="mt-1 w-full rounded border-slate-300"></label>
                <div class="self-end"><button class="rounded bg-slate-900 px-4 py-2 text-white">Enregistrer</button></div>
            </form></section>
        @endif

        <section class="rounded-xl bg-white p-5 shadow-sm"><h2 class="font-semibold">Paiements compatibles et allocations</h2><div class="mt-4 space-y-4 text-sm">@forelse($payments as $payment)
            @php($allocatedHere = $payment->allocations->firstWhere('invoice_id', $invoice->id))
            <article class="rounded-lg border p-4"><div class="flex flex-wrap justify-between gap-2"><p><strong>{{ $payment->payment_number }}</strong> · {{ $payment->amount }} {{ $payment->currency }}</p><span>{{ $payment->status }}</span></div>
                <div class="mt-3 flex flex-wrap gap-2">
                    @if(!$allocatedHere && in_array($payment->status, ['pending','posted']) && auth()->user()->hasPermission('payment.allocate'))<form method="POST" action="{{ route('finance.allocations.store', [$payment, $invoice]) }}" class="flex gap-2">@csrf<input name="amount" inputmode="decimal" required value="{{ $invoice->balance_due }}" class="w-32 rounded border-slate-300"><button class="rounded border px-3 py-2">Allouer</button></form>@elseif($allocatedHere)<span class="rounded bg-emerald-50 px-3 py-2 text-emerald-800">Alloué : {{ $allocatedHere->amount }} {{ $invoice->currency }}</span>@endif
                    @if($payment->status === 'pending' && auth()->user()->hasPermission('payment.post'))<form method="POST" action="{{ route('finance.payments.post', $payment) }}" onsubmit="return confirm('Comptabiliser ce paiement ?')">@csrf<button class="rounded bg-emerald-700 px-3 py-2 text-white">Comptabiliser</button></form>@endif
                    @if($payment->status === 'posted' && auth()->user()->hasPermission('payment.reverse'))<form method="POST" action="{{ route('finance.payments.reverse', $payment) }}" class="flex gap-2" onsubmit="return confirm('Créer une contrepassation append-only ?')">@csrf<input type="hidden" name="idempotency_key" value="web-reverse-{{ Illuminate\Support\Str::uuid() }}"><input name="reason" required placeholder="Motif obligatoire" class="rounded border-slate-300"><button class="rounded border border-red-300 px-3 py-2 text-red-700">Contrepasser</button></form>@endif
                </div>
            </article>
        @empty<p class="text-slate-500">Aucun paiement compatible.</p>@endforelse</div></section>

        @if($invoice->status === 'paid' && auth()->user()->hasPermission('contract.close'))<form method="POST" action="{{ route('finance.contracts.close', $invoice->rentalContract) }}" onsubmit="return confirm('Clôturer financièrement ce contrat ?')">@csrf<button class="rounded bg-slate-900 px-4 py-2 text-white">Clôturer le contrat si la caution est soldée</button></form>@endif
    </div>
</x-app-layout>
