<x-app-layout>
    <article class="mx-auto max-w-4xl rounded-xl bg-white p-8 shadow-sm print:shadow-none">
        <div class="flex flex-wrap items-start justify-between gap-4"><div><p class="text-sm text-slate-500">Facture</p><h1 class="text-3xl font-bold">{{ $invoice->invoice_number }}</h1><p class="mt-1 text-sm">Contrat {{ $invoice->contract_snapshot['number'] ?? '' }}</p></div><div class="text-right"><p class="font-semibold">{{ strtoupper($invoice->status) }}</p><p class="text-sm text-slate-500">{{ $invoice->issued_at?->format('d/m/Y H:i') ?? 'Brouillon' }}</p></div></div>
        <div class="mt-8 rounded-lg bg-slate-50 p-4 text-sm"><p class="font-medium">{{ $invoice->customer_snapshot['name'] ?? 'Client' }}</p><p>{{ $invoice->customer_snapshot['city'] ?? '' }}</p></div>
        <table class="mt-8 min-w-full text-sm"><thead><tr class="border-b text-left text-slate-500"><th class="py-3">Description</th><th>HT</th><th>Taxe</th><th>Total</th></tr></thead><tbody>@foreach($invoice->lines as $line)<tr class="border-b"><td class="py-3">{{ $line->description }}</td><td>{{ $line->subtotal }}</td><td>{{ $line->tax_amount }}</td><td>{{ $line->total_amount }}</td></tr>@endforeach</tbody></table>
        <div class="mt-6 ml-auto max-w-xs space-y-2 text-sm"><p class="flex justify-between"><span>Sous-total</span><strong>{{ $invoice->subtotal }}</strong></p><p class="flex justify-between"><span>Taxe ({{ $invoice->tax_mode }})</span><strong>{{ $invoice->tax_amount }}</strong></p><p class="flex justify-between text-lg"><span>Total</span><strong>{{ $invoice->total_amount }} {{ $invoice->currency }}</strong></p><p class="flex justify-between"><span>Payé</span><strong>{{ $invoice->paid_amount }}</strong></p><p class="flex justify-between"><span>Solde</span><strong>{{ $invoice->balance_due }}</strong></p></div>
        <p class="mt-8 text-xs text-slate-500">Document opérationnel RentFleet. Les règles fiscales sont configurables et ne constituent pas un calcul fiscal officiel.</p>
        @if($invoice->status === 'draft' && auth()->user()->hasPermission('invoice.issue'))<form class="mt-6 print:hidden" method="POST" action="{{ route('finance.invoices.issue', $invoice) }}">@csrf<button class="rounded-lg bg-slate-900 px-4 py-2 text-sm text-white">Émettre et figer</button></form>@endif
        @if($invoice->status === 'issued' && $invoice->paid_amount === '0.00' && auth()->user()->hasPermission('invoice.void'))<form class="mt-6 flex gap-3 print:hidden" method="POST" action="{{ route('finance.invoices.void', $invoice) }}">@csrf<input name="reason" required placeholder="Motif d’annulation" class="rounded-lg border-slate-300"><button class="rounded-lg border border-red-300 px-4 py-2 text-sm text-red-700">Annuler la facture</button></form>@endif
    </article>
</x-app-layout>
