
<x-app-layout>
    @php($departure = $contract->inspections->firstWhere('inspection_type.value', 'departure'))
    @php($return = $contract->inspections->firstWhere('inspection_type.value', 'return'))
    <div class="mx-auto max-w-7xl space-y-6">
        <div class="flex flex-wrap items-center justify-between gap-3"><div><p class="text-sm text-slate-500">{{ $contract->status->label() }}</p><h1 class="text-2xl font-bold">{{ $contract->contract_number }}</h1></div><a href="{{ route('contracts.print', $contract) }}" class="rounded-lg border bg-white px-4 py-2 text-sm">Version imprimable</a></div>
        @if($errors->any())<div class="rounded-lg bg-red-50 p-4 text-sm text-red-800">{{ $errors->first() }}</div>@endif
        <div class="grid gap-6 lg:grid-cols-3">
            <section class="rounded-xl bg-white p-5 shadow-sm lg:col-span-2"><h2 class="font-semibold">Synthèse</h2><dl class="mt-4 grid grid-cols-2 gap-3 text-sm"><dt class="text-slate-500">Réservation</dt><dd><a class="underline" href="{{ route('reservations.show', $contract->reservation) }}">{{ $contract->reservation->reservation_number }}</a></dd><dt class="text-slate-500">Client</dt><dd>{{ $contract->customer->displayName() }}</dd><dt class="text-slate-500">Véhicule</dt><dd>{{ $contract->vehicle->registration_number }}</dd><dt class="text-slate-500">Conducteur principal</dt><dd>{{ optional($contract->drivers->firstWhere('is_primary', true)?->driver)->first_name }} {{ optional($contract->drivers->firstWhere('is_primary', true)?->driver)->last_name }}</dd><dt class="text-slate-500">Période</dt><dd>{{ $contract->expected_start_at->format('d/m/Y H:i') }} — {{ $contract->expected_return_at->format('d/m/Y H:i') }}</dd><dt class="text-slate-500">Location</dt><dd>{{ $contract->rental_subtotal }} {{ $contract->currency }}</dd><dt class="text-slate-500">Frais approuvés</dt><dd>{{ $contract->additional_charges_total }} {{ $contract->currency }}</dd><dt class="font-semibold">Total</dt><dd class="font-semibold">{{ $contract->total_amount }} {{ $contract->currency }}</dd></dl></section>
            <section class="rounded-xl bg-white p-5 shadow-sm"><h2 class="font-semibold">Version courante</h2><p class="mt-3 text-sm">Version {{ $contract->currentVersion?->version_number ?? '—' }}</p><p class="mt-1 break-all text-xs text-slate-500">{{ $contract->currentVersion?->content_hash }}</p><p class="mt-2 text-xs">{{ $contract->currentVersion?->locked_at ? 'Verrouillée après acceptation' : 'Modifiable uniquement par nouvelle version' }}</p>@if($contract->currentVersion?->document)<p class="mt-2 text-xs text-emerald-700">Fichier privé vérifiable associé.</p>@can('view', $contract->currentVersion->document)<a href="{{ route('documents.show', $contract->currentVersion->document) }}" class="mt-2 inline-block text-xs underline">Voir le document</a>@endcan @elseif(in_array($contract->status->value, ['draft','ready']))@can('version', $contract)<form method="POST" enctype="multipart/form-data" action="{{ route('contracts.version-document.store', $contract) }}" class="mt-4 space-y-2">@csrf<label class="block text-xs">PDF contractuel privé<input type="file" name="file" required class="mt-1 block w-full text-sm"></label><button class="rounded-lg border px-3 py-2 text-sm">Associer le fichier</button></form>@endcan @endif @can('version', $contract)<form method="POST" action="{{ route('contracts.versions.store', $contract) }}" class="mt-4 space-y-2">@csrf<input name="change_reason" required placeholder="Motif de la nouvelle version" class="w-full rounded-lg border-slate-300 text-sm"><button class="rounded-lg border px-3 py-2 text-sm">Créer une version</button></form>@endcan</section>
        </div>

        <section class="rounded-xl bg-white p-5 shadow-sm"><h2 class="font-semibold">Actions du cycle</h2><div class="mt-4 flex flex-wrap gap-3">
            @if($contract->status->value === 'draft')@can('version', $contract)<form method="POST" action="{{ route('contracts.ready', $contract) }}">@csrf<button class="rounded-lg bg-slate-900 px-4 py-2 text-sm text-white">Marquer prêt</button></form>@endcan @endif
            @if($contract->status->value === 'ready')@can('accept', $contract)<form method="POST" action="{{ route('contracts.accept', $contract) }}" class="flex flex-wrap gap-2">@csrf<input name="accepted_by_name" required placeholder="Nom du signataire" class="rounded-lg border-slate-300 text-sm"><select name="acceptance_method" class="rounded-lg border-slate-300 text-sm">@foreach($acceptanceMethods as $method)<option value="{{ $method->value }}">{{ $method->value }}</option>@endforeach</select><button class="rounded-lg bg-emerald-700 px-4 py-2 text-sm text-white">Enregistrer l’acceptation</button></form>@endcan @endif
            @if(in_array($contract->status->value, ['draft','ready']))@can('cancel', $contract)<form method="POST" action="{{ route('contracts.cancel', $contract) }}" class="flex gap-2">@csrf<input name="reason" required placeholder="Motif" class="rounded-lg border-slate-300 text-sm"><button class="rounded-lg bg-red-700 px-4 py-2 text-sm text-white">Annuler</button></form>@endcan @endif
        </div></section>

        @if($contract->status->value === 'accepted' && !$departure)
        <section class="rounded-xl bg-white p-5 shadow-sm"><h2 class="font-semibold">Inspection de départ</h2><form method="POST" action="{{ route('contracts.departure-inspection', $contract) }}" class="mt-4 space-y-4">@csrf
            <div class="grid gap-3 md:grid-cols-3"><input type="number" name="mileage" required min="0" placeholder="Kilométrage" class="rounded-lg border-slate-300"><input type="number" name="fuel_level" required min="0" max="100" step="0.01" placeholder="Carburant %" class="rounded-lg border-slate-300"><input name="notes" placeholder="Notes" class="rounded-lg border-slate-300"></div>
            <div class="grid gap-3 md:grid-cols-2">@foreach(['body'=>'Carrosserie','interior'=>'Habitacle','tyres'=>'Pneus','equipment'=>'Équipements'] as $code => $label)<div class="flex gap-2"><input type="hidden" name="items[{{ $loop->index }}][item_code]" value="{{ $code }}"><input type="hidden" name="items[{{ $loop->index }}][label]" value="{{ $label }}"><span class="w-32 py-2 text-sm">{{ $label }}</span><select name="items[{{ $loop->index }}][condition]" class="flex-1 rounded-lg border-slate-300"><option value="good">Bon</option><option value="damaged">Endommagé</option><option value="missing">Manquant</option><option value="not_checked">Non contrôlé</option></select></div>@endforeach</div><button class="rounded-lg bg-slate-900 px-4 py-2 text-white">Terminer l’inspection</button>
        </form></section>
        @elseif($contract->status->value === 'accepted' && $departure)
        @can('activate', $contract)<form method="POST" action="{{ route('contracts.activate', $contract) }}">@csrf<button class="rounded-lg bg-emerald-700 px-4 py-2 text-white">Activer le contrat et remettre le véhicule</button></form>@endcan
        @endif

        @if($contract->status->value === 'active')
        <section class="rounded-xl bg-white p-5 shadow-sm"><h2 class="font-semibold">Inspection de retour</h2><form method="POST" action="{{ route('contracts.return-inspection', $contract) }}" class="mt-4 space-y-4">@csrf
            <div class="grid gap-3 md:grid-cols-3"><input type="number" name="mileage" required min="{{ $contract->start_mileage }}" placeholder="Kilométrage retour" class="rounded-lg border-slate-300"><input type="number" name="fuel_level" required min="0" max="100" step="0.01" placeholder="Carburant %" class="rounded-lg border-slate-300"><input name="notes" placeholder="Notes" class="rounded-lg border-slate-300"></div>
            <div class="grid gap-3 md:grid-cols-2">@foreach(['body'=>'Carrosserie','interior'=>'Habitacle','tyres'=>'Pneus','equipment'=>'Équipements'] as $code => $label)<div class="flex gap-2"><input type="hidden" name="items[{{ $loop->index }}][item_code]" value="{{ $code }}"><input type="hidden" name="items[{{ $loop->index }}][label]" value="{{ $label }}"><span class="w-32 py-2 text-sm">{{ $label }}</span><select name="items[{{ $loop->index }}][condition]" class="flex-1 rounded-lg border-slate-300"><option value="good">Bon</option><option value="damaged">Endommagé</option><option value="missing">Manquant</option><option value="not_checked">Non contrôlé</option></select></div>@endforeach</div><button class="rounded-lg bg-slate-900 px-4 py-2 text-white">Terminer le retour</button>
        </form></section>
        @endif

        @if($contract->status->value === 'return_pending')
        <div class="grid gap-6 lg:grid-cols-2">
            <section class="rounded-xl bg-white p-5 shadow-sm"><h2 class="font-semibold">Dommages</h2>@foreach($contract->damages as $damage)<div class="mt-4 border-t pt-3 text-sm"><p class="font-medium">{{ $damage->damage_number }} — {{ $damage->description }}</p><p>{{ $damage->severity->value }} / {{ $damage->responsibility->value }} / {{ $damage->status->value }}</p>@if(in_array($damage->severity->value, ['major','critical']))<p class="mt-2 rounded bg-amber-50 p-2 text-amber-900">Mise hors service recommandée. Une confirmation humaine reste requise depuis la fiche véhicule.</p>@endif @can('review', $damage)<form method="POST" action="{{ route('damages.review', $damage) }}" class="mt-2 grid gap-2">@csrf<select name="responsibility" class="rounded border-slate-300"><option value="customer">Client</option><option value="agency">Agence</option><option value="insurance">Assurance</option><option value="unknown">Indéterminée</option></select><select name="status" class="rounded border-slate-300"><option value="resolved">Résolu</option><option value="dismissed">Écarté</option></select><input name="approved_cost" type="number" step="0.01" min="0" placeholder="Coût approuvé si client" class="rounded border-slate-300"><input name="reason" required placeholder="Justification humaine" class="rounded border-slate-300"><button class="rounded bg-slate-900 px-3 py-2 text-white">Enregistrer la revue</button></form>@endcan</div>@endforeach
            @can('return', $contract)<form method="POST" action="{{ route('contracts.damages.store', $contract) }}" class="mt-5 grid gap-2">@csrf<input type="hidden" name="return_inspection_id" value="{{ $return?->id }}"><input name="description" required placeholder="Description du dommage" class="rounded border-slate-300"><input name="vehicle_area" placeholder="Zone du véhicule" class="rounded border-slate-300"><select name="severity" class="rounded border-slate-300"><option value="minor">Mineur</option><option value="moderate">Modéré</option><option value="major">Majeur</option><option value="critical">Critique</option></select><input name="estimated_cost" type="number" step="0.01" min="0" placeholder="Estimation indicative" class="rounded border-slate-300"><button class="rounded border px-3 py-2">Signaler — responsabilité en attente</button></form>@endcan</section>
            <section class="rounded-xl bg-white p-5 shadow-sm"><h2 class="font-semibold">Frais de retour</h2>@can('return', $contract)<form method="POST" action="{{ route('contracts.charges', $contract) }}" class="mt-3 flex flex-wrap gap-2">@csrf<label class="text-sm"><input type="checkbox" name="cleaning_approved" value="1"> Nettoyage constaté et approuvé</label><input name="cleaning_amount" type="number" step="0.01" min="0" placeholder="Montant" class="rounded border-slate-300"><button class="rounded border px-3 py-2">Calculer les propositions</button></form>@endcan
            <form method="POST" action="{{ route('contracts.returned', $contract) }}" class="mt-5 space-y-3">@csrf @forelse($contract->charges as $charge)<div class="rounded border p-3 text-sm"><p class="font-medium">{{ $charge->description }} — {{ $charge->total_amount }} {{ $contract->currency }}</p><label class="mr-4"><input type="checkbox" name="approved_charge_ids[]" value="{{ $charge->id }}" @checked($charge->status->value === 'approved')> Approuver</label><label><input type="checkbox" name="rejected_charge_ids[]" value="{{ $charge->id }}" @checked($charge->status->value === 'rejected')> Rejeter</label></div>@empty<p class="text-sm text-slate-500">Aucun frais proposé.</p>@endforelse<input name="reason" placeholder="Note de retour" class="w-full rounded border-slate-300"><button class="rounded bg-emerald-700 px-4 py-2 text-white">Finaliser le retour</button></form></section>
        </div>
        @endif

        @if($comparison)<section class="rounded-xl bg-white p-5 shadow-sm"><h2 class="font-semibold">Comparaison départ / retour</h2><div class="mt-3 grid gap-3 text-sm md:grid-cols-3"><p>Kilométrage : <strong>+{{ $comparison['mileage_delta'] }} km</strong></p><p>Carburant : <strong>{{ $comparison['fuel_delta'] }} point(s)</strong></p><p>Anomalies à revoir : <strong>{{ count($comparison['damage_candidates']) }}</strong></p></div><ul class="mt-3 text-sm">@foreach($comparison['items'] as $item)<li>{{ $item['label'] }} : {{ $item['before'] }} → {{ $item['after'] }}</li>@endforeach</ul></section>@endif
        @if($contract->inspections->isNotEmpty() || $contract->damages->isNotEmpty())<section class="rounded-xl bg-white p-5 shadow-sm"><h2 class="font-semibold">Photos privées</h2><p class="mt-2 text-sm text-slate-500">Les fichiers passent par le stockage privé existant ; aucune URL publique n’est créée.</p><div class="mt-4 grid gap-4 lg:grid-cols-2">@foreach($contract->inspections as $inspection)@can('manage', $inspection)<form method="POST" enctype="multipart/form-data" action="{{ route('inspections.documents.store', $inspection) }}" class="rounded border p-3 text-sm">@csrf<input type="hidden" name="document_type" value="inspection_photo"><input type="hidden" name="title" value="Photo inspection {{ $inspection->inspection_type->value }}"><input type="hidden" name="is_sensitive" value="1"><label>Photo inspection {{ $inspection->inspection_type->value }} <input type="file" name="file" required class="mt-2 block w-full"></label><button class="mt-2 rounded border px-3 py-2">Ajouter en privé</button></form>@endcan @endforeach @foreach($contract->damages as $damage)@can('report', $damage)<form method="POST" enctype="multipart/form-data" action="{{ route('damages.documents.store', $damage) }}" class="rounded border p-3 text-sm">@csrf<input type="hidden" name="document_type" value="damage_photo"><input type="hidden" name="title" value="Photo dommage {{ $damage->damage_number }}"><input type="hidden" name="is_sensitive" value="1"><label>Photo {{ $damage->damage_number }} <input type="file" name="file" required class="mt-2 block w-full"></label><button class="mt-2 rounded border px-3 py-2">Ajouter en privé</button></form>@endcan @endforeach</div></section>@endif
        <section class="rounded-xl bg-white p-5 shadow-sm"><h2 class="font-semibold">Historique</h2><ol class="mt-4 space-y-2 text-sm">@foreach($contract->statusHistories->sortByDesc('created_at') as $history)<li class="border-l-2 border-slate-300 pl-3">{{ $history->from_status?->label() ?? 'Création' }} → {{ $history->to_status->label() }} <span class="text-slate-500">{{ $history->created_at->format('d/m/Y H:i') }}</span></li>@endforeach</ol></section>
    </div>
</x-app-layout>

