
<x-app-layout>
    @php($departure = $contract->inspections->firstWhere('inspection_type.value', 'departure'))
    @php($return = $contract->inspections->firstWhere('inspection_type.value', 'return'))
    <div class="rf-page">
        <x-page-header :title="$contract->contract_number" eyebrow="Contrat de location" description="Cycle contractuel, preuves documentaires et situation financière dans la devise du contrat."><x-slot:actions><x-status-badge :value="$contract->status" /><a href="{{ route('contracts.print', $contract) }}" class="rf-button-secondary">Version imprimable</a></x-slot:actions></x-page-header>
        <x-form-errors />
        @include('contracts.partials.workflow-status')
        <div class="grid gap-6 lg:grid-cols-3">
            <x-section-card title="Synthèse" class="lg:col-span-2"><x-metadata-list><x-metadata-item label="Réservation"><a href="{{ route('reservations.show', $contract->reservation) }}">{{ $contract->reservation->reservation_number }}</a></x-metadata-item><x-metadata-item label="Client">{{ $contract->customer->displayName() }}</x-metadata-item><x-metadata-item label="Véhicule">{{ $contract->vehicle->registration_number }}</x-metadata-item><x-metadata-item label="Conducteur principal">{{ optional($contract->drivers->firstWhere('is_primary', true)?->driver)->first_name }} {{ optional($contract->drivers->firstWhere('is_primary', true)?->driver)->last_name }}</x-metadata-item><x-metadata-item label="Période">{{ App\Support\Ui\UiLabel::dateTime($contract->expected_start_at) }} — {{ App\Support\Ui\UiLabel::dateTime($contract->expected_return_at) }}</x-metadata-item><x-metadata-item label="Location">{{ App\Support\Ui\UiLabel::money($contract->rental_subtotal, $contract->currency) }}</x-metadata-item><x-metadata-item label="Frais approuvés">{{ App\Support\Ui\UiLabel::money($contract->additional_charges_total, $contract->currency) }}</x-metadata-item><x-metadata-item label="Total"><strong>{{ App\Support\Ui\UiLabel::money($contract->total_amount, $contract->currency) }}</strong></x-metadata-item></x-metadata-list></x-section-card>
            <x-section-card title="Version courante" description="Les empreintes techniques sont contrôlées sans être exposées dans l’interface."><p class="text-sm font-medium">Version {{ $contract->currentVersion?->version_number ?? '—' }}</p><p class="mt-2 text-xs">{{ $contract->currentVersion?->locked_at ? 'Verrouillée après acceptation' : 'Toute modification crée une nouvelle version' }}</p>@if($contract->currentVersion?->document)<p class="mt-2 text-xs text-emerald-700">Fichier privé vérifiable associé.</p>@can('view', $contract->currentVersion->document)<a href="{{ route('documents.show', $contract->currentVersion->document) }}" class="rf-button-link mt-2">Voir le document</a>@endcan @elseif(in_array($contract->status->value, ['draft','ready']))@can('version', $contract)<form method="POST" enctype="multipart/form-data" action="{{ route('contracts.version-document.store', $contract) }}" class="mt-4 space-y-2">@csrf<label class="rf-field-label" for="contract-version-file">PDF contractuel <span class="text-red-700">*</span></label><input id="contract-version-file" type="file" name="file" required class="block w-full text-sm"><x-field-error :messages="$errors->get('file')" /><x-primary-button>Associer le fichier</x-primary-button></form>@endcan @endif @can('version', $contract)<form method="POST" action="{{ route('contracts.versions.store', $contract) }}" class="mt-4 space-y-2">@csrf<label class="rf-field-label" for="change-reason">Motif de la nouvelle version <span class="text-red-700">*</span></label><input id="change-reason" name="change_reason" required value="{{ old('change_reason') }}" class="w-full"><x-field-error :messages="$errors->get('change_reason')" /><x-secondary-button type="submit">Créer une version</x-secondary-button></form>@endcan</x-section-card>
        </div>

        <section class="rounded-xl bg-white p-5 shadow-sm"><h2 class="font-semibold">Actions du cycle</h2><div class="mt-4 flex flex-wrap gap-3">
            @if($contract->status->value === 'draft')@can('version', $contract)<form method="POST" action="{{ route('contracts.ready', $contract) }}">@csrf<button class="rounded-lg bg-slate-900 px-4 py-2 text-sm text-white">Marquer prêt</button></form>@endcan @endif
            @if($contract->status->value === 'ready')@can('accept', $contract)<form method="POST" action="{{ route('contracts.accept', $contract) }}" class="flex flex-wrap gap-2">@csrf<input name="accepted_by_name" required value="{{ old('accepted_by_name') }}" aria-label="Nom du signataire" placeholder="Nom du signataire" class="text-sm"><select name="acceptance_method" aria-label="Mode d’acceptation" class="text-sm">@foreach($acceptanceMethods as $method)<option value="{{ $method->value }}">{{ App\Support\Ui\UiLabel::get($method) }}</option>@endforeach</select><x-primary-button>Enregistrer l’acceptation</x-primary-button></form>@endcan @endif
            @if(in_array($contract->status->value, ['draft','ready']))@can('cancel', $contract)<form method="POST" action="{{ route('contracts.cancel', $contract) }}" class="flex gap-2">@csrf<input name="reason" required placeholder="Motif" class="rounded-lg border-slate-300 text-sm"><button class="rounded-lg bg-red-700 px-4 py-2 text-sm text-white">Annuler</button></form>@endcan @endif
        </div></section>

        @if($contract->status->value === 'accepted' && !$departure && auth()->user()->hasPermission('inspection.manage'))
        <section class="rounded-xl bg-white p-5 shadow-sm"><h2 class="font-semibold">Inspection de départ</h2><form method="POST" action="{{ route('contracts.departure-inspection', $contract) }}" class="mt-4 space-y-4">@csrf
            <div class="grid gap-3 md:grid-cols-3"><input type="number" name="mileage" required min="0" placeholder="Kilométrage" class="rounded-lg border-slate-300"><input type="number" name="fuel_level" required min="0" max="100" step="0.01" placeholder="Carburant %" class="rounded-lg border-slate-300"><input name="notes" placeholder="Notes" class="rounded-lg border-slate-300"></div>
            <div class="grid gap-3 md:grid-cols-2">@foreach(['body'=>'Carrosserie','interior'=>'Habitacle','tyres'=>'Pneus','equipment'=>'Équipements'] as $code => $label)<div class="flex gap-2"><input type="hidden" name="items[{{ $loop->index }}][item_code]" value="{{ $code }}"><input type="hidden" name="items[{{ $loop->index }}][label]" value="{{ $label }}"><span class="w-32 py-2 text-sm">{{ $label }}</span><select name="items[{{ $loop->index }}][condition]" class="flex-1 rounded-lg border-slate-300"><option value="good">Bon</option><option value="damaged">Endommagé</option><option value="missing">Manquant</option><option value="not_checked">Non contrôlé</option></select></div>@endforeach</div><button class="rounded-lg bg-slate-900 px-4 py-2 text-white">Terminer l’inspection</button>
        </form></section>
        @elseif($contract->status->value === 'accepted' && $departure)
        @can('activate', $contract)<form method="POST" action="{{ route('contracts.activate', $contract) }}">@csrf<button class="rounded-lg bg-emerald-700 px-4 py-2 text-white">Activer le contrat et remettre le véhicule</button></form>@endcan
        @endif

        @if($contract->status->value === 'active' && auth()->user()->hasPermission('inspection.manage'))
        <section class="rounded-xl bg-white p-5 shadow-sm"><h2 class="font-semibold">Inspection de retour</h2><form method="POST" action="{{ route('contracts.return-inspection', $contract) }}" class="mt-4 space-y-4">@csrf
            <div class="grid gap-3 md:grid-cols-3"><input type="number" name="mileage" required min="{{ $contract->start_mileage }}" placeholder="Kilométrage retour" class="rounded-lg border-slate-300"><input type="number" name="fuel_level" required min="0" max="100" step="0.01" placeholder="Carburant %" class="rounded-lg border-slate-300"><input name="notes" placeholder="Notes" class="rounded-lg border-slate-300"></div>
            <div class="grid gap-3 md:grid-cols-2">@foreach(['body'=>'Carrosserie','interior'=>'Habitacle','tyres'=>'Pneus','equipment'=>'Équipements'] as $code => $label)<div class="flex gap-2"><input type="hidden" name="items[{{ $loop->index }}][item_code]" value="{{ $code }}"><input type="hidden" name="items[{{ $loop->index }}][label]" value="{{ $label }}"><span class="w-32 py-2 text-sm">{{ $label }}</span><select name="items[{{ $loop->index }}][condition]" class="flex-1 rounded-lg border-slate-300"><option value="good">Bon</option><option value="damaged">Endommagé</option><option value="missing">Manquant</option><option value="not_checked">Non contrôlé</option></select></div>@endforeach</div><button class="rounded-lg bg-slate-900 px-4 py-2 text-white">Terminer le retour</button>
        </form></section>
        @endif

        @if($contract->status->value === 'return_pending')
        <div class="grid gap-6 lg:grid-cols-2">
            <section class="rounded-xl bg-white p-5 shadow-sm"><h2 class="font-semibold">Dommages</h2>@foreach($contract->damages as $damage)<div class="mt-4 border-t pt-3 text-sm"><p class="font-medium">{{ $damage->damage_number }} — {{ $damage->description }}</p><div class="mt-2 flex flex-wrap gap-2"><x-status-badge :value="$damage->severity" /><x-status-badge :value="$damage->responsibility" /><x-status-badge :value="$damage->status" /></div>@if(in_array($damage->severity->value, ['major','critical']))<p class="mt-2 rounded bg-amber-50 p-2 text-amber-900">Mise hors service recommandée. Une confirmation humaine reste requise depuis la fiche véhicule.</p>@endif @can('review', $damage)<form method="POST" action="{{ route('damages.review', $damage) }}" class="mt-2 grid gap-2">@csrf<select name="responsibility" aria-label="Responsabilité"><option value="customer">Client</option><option value="agency">Agence</option><option value="insurance">Assurance</option><option value="unknown">Indéterminée</option></select><select name="status" aria-label="Décision"><option value="resolved">Résolu</option><option value="dismissed">Écarté</option></select><input name="approved_cost" type="number" step="0.01" min="0" aria-label="Coût approuvé" placeholder="Coût approuvé ({{ $contract->currency }})"><input name="reason" required aria-label="Justification humaine" placeholder="Justification humaine"><x-primary-button>Enregistrer la revue</x-primary-button></form>@endcan</div>@endforeach
            @if(auth()->user()->hasPermission('damage.report'))@can('return', $contract)<form method="POST" action="{{ route('contracts.damages.store', $contract) }}" class="mt-5 grid gap-2">@csrf<input type="hidden" name="return_inspection_id" value="{{ $return?->id }}"><input name="description" required placeholder="Description du dommage" class="rounded border-slate-300"><input name="vehicle_area" placeholder="Zone du véhicule" class="rounded border-slate-300"><select name="severity" class="rounded border-slate-300"><option value="minor">Mineur</option><option value="moderate">Modéré</option><option value="major">Majeur</option><option value="critical">Critique</option></select><input name="estimated_cost" type="number" step="0.01" min="0" placeholder="Estimation indicative" class="rounded border-slate-300"><button class="rounded border px-3 py-2">Signaler — responsabilité en attente</button></form>@endcan @endif</section>
            <section class="rounded-xl bg-white p-5 shadow-sm"><h2 class="font-semibold">Frais de retour</h2>@if(auth()->user()->hasPermission('charge.review'))@can('return', $contract)<form method="POST" action="{{ route('contracts.charges', $contract) }}" class="mt-3 flex flex-wrap gap-2">@csrf<label class="text-sm"><input type="checkbox" name="cleaning_approved" value="1"> Nettoyage constaté et approuvé</label><input name="cleaning_amount" type="number" step="0.01" min="0" placeholder="Montant" class="rounded border-slate-300"><button class="rounded border px-3 py-2">Calculer les propositions</button></form>@endcan
            @can('return', $contract)<form method="POST" action="{{ route('contracts.returned', $contract) }}" class="mt-5 space-y-3">@csrf @forelse($contract->charges as $charge)<div class="rounded border p-3 text-sm"><p class="font-medium">{{ $charge->description }} — {{ App\Support\Ui\UiLabel::money($charge->total_amount, $contract->currency) }}</p><label class="mr-4"><input type="checkbox" name="approved_charge_ids[]" value="{{ $charge->id }}" @checked($charge->status->value === 'approved')> Approuver</label><label><input type="checkbox" name="rejected_charge_ids[]" value="{{ $charge->id }}" @checked($charge->status->value === 'rejected')> Rejeter</label></div>@empty<p class="text-sm text-slate-500">Aucun frais proposé.</p>@endforelse<input name="reason" placeholder="Note de retour" class="w-full"><x-primary-button>Finaliser le retour</x-primary-button></form>@endcan @endif</section>
        </div>
        @endif

        @if($comparison)<section class="rounded-xl bg-white p-5 shadow-sm"><h2 class="font-semibold">Comparaison départ / retour</h2><div class="mt-3 grid gap-3 text-sm md:grid-cols-3"><p>Kilométrage : <strong>+{{ $comparison['mileage_delta'] }} km</strong></p><p>Carburant : <strong>{{ $comparison['fuel_delta'] }} point(s)</strong></p><p>Anomalies à revoir : <strong>{{ count($comparison['damage_candidates']) }}</strong></p></div><ul class="mt-3 text-sm">@foreach($comparison['items'] as $item)<li>{{ $item['label'] }} : {{ App\Support\Ui\UiLabel::get($item['before']) }} → {{ App\Support\Ui\UiLabel::get($item['after']) }}</li>@endforeach</ul></section>@endif
        @if($contract->inspections->isNotEmpty() || $contract->damages->isNotEmpty())<section class="rounded-xl bg-white p-5 shadow-sm"><h2 class="font-semibold">Photos privées</h2><p class="mt-2 text-sm text-slate-500">Les fichiers passent par le stockage privé existant ; aucune URL publique n’est créée.</p><div class="mt-4 grid gap-4 lg:grid-cols-2">@foreach($contract->inspections as $inspection)@can('manage', $inspection)<form method="POST" enctype="multipart/form-data" action="{{ route('inspections.documents.store', $inspection) }}" class="rounded border p-3 text-sm">@csrf<input type="hidden" name="document_type" value="inspection_photo"><input type="hidden" name="title" value="Photo inspection {{ $inspection->inspection_type->value }}"><input type="hidden" name="is_sensitive" value="1"><label>Photo inspection {{ $inspection->inspection_type->value }} <input type="file" name="file" required class="mt-2 block w-full"></label><button class="mt-2 rounded border px-3 py-2">Ajouter en privé</button></form>@endcan @endforeach @foreach($contract->damages as $damage)@can('report', $damage)<form method="POST" enctype="multipart/form-data" action="{{ route('damages.documents.store', $damage) }}" class="rounded border p-3 text-sm">@csrf<input type="hidden" name="document_type" value="damage_photo"><input type="hidden" name="title" value="Photo dommage {{ $damage->damage_number }}"><input type="hidden" name="is_sensitive" value="1"><label>Photo {{ $damage->damage_number }} <input type="file" name="file" required class="mt-2 block w-full"></label><button class="mt-2 rounded border px-3 py-2">Ajouter en privé</button></form>@endcan @endforeach</div></section>@endif
        @include('contracts.partials.finance')
        <x-section-card title="Historique du contrat"><x-timeline label="Cycle du contrat">@foreach($contract->statusHistories->sortByDesc('created_at') as $history)<x-timeline-item :title="($history->from_status?->label() ?? 'Création').' → '.$history->to_status->label()" :meta="App\Support\Ui\UiLabel::dateTime($history->created_at)" :active="$loop->first"></x-timeline-item>@endforeach</x-timeline></x-section-card>
    </div>
</x-app-layout>
