<x-app-layout>
    <div class="space-y-7">
        <x-page-header title="Assurance" eyebrow="Couvertures et sinistres" description="Les références sensibles restent chiffrées et masquées. Toute décision de sinistre reste humaine."><x-slot:actions>@can('create', App\Models\InsurancePolicy::class)<a href="{{ route('insurance.policies.create') }}" class="rounded-lg border bg-white px-4 py-2 text-sm">Nouvelle police</a>@endcan @can('create', App\Models\InsuranceClaim::class)<a href="{{ route('insurance.claims.create') }}" class="rounded-lg bg-slate-900 px-4 py-2 text-sm text-white">Déclarer un sinistre</a>@endcan</x-slot:actions></x-page-header>
        <x-form-errors />
        @can('create', App\Models\InsuranceCompany::class)<form method="POST" action="{{ route('insurance.companies.store') }}" class="grid gap-3 rounded-xl bg-white p-5 shadow-sm md:grid-cols-4">@csrf<label class="text-sm">Compagnie *<input name="name" required value="{{ old('name') }}" class="mt-1 w-full rounded border-slate-300"><x-input-error :messages="$errors->get('name')" /></label><label class="text-sm">E-mail<input name="email" type="email" value="{{ old('email') }}" class="mt-1 w-full rounded border-slate-300"></label><label class="text-sm">Téléphone<input name="phone" value="{{ old('phone') }}" class="mt-1 w-full rounded border-slate-300"></label><div class="self-end"><button class="rounded-lg bg-slate-900 px-4 py-2 text-white">Ajouter</button></div></form>@endcan
        <section class="rounded-xl bg-white p-6 shadow-sm"><div class="flex flex-wrap items-center justify-between gap-3"><h2 class="font-semibold">Compagnies</h2><x-result-count :paginator="$companies" /></div><form method="GET" class="mt-4 flex flex-wrap gap-3"><input name="company_q" value="{{ request('company_q') }}" placeholder="Rechercher une compagnie" class="min-w-64 rounded border-slate-300"><button class="rounded bg-slate-900 px-4 py-2 text-white">Filtrer</button></form><div class="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">@forelse($companies as $company)<a href="{{ route('insurance.companies.show', $company) }}" class="rounded-lg border p-4"><div class="flex items-center justify-between gap-2"><strong>{{ $company->name }}</strong><x-status-badge :value="$company->is_active ? 'active' : 'inactive'" /></div><p class="mt-2 text-sm text-slate-500">{{ $company->policies_count }} police(s) visible(s)</p></a>@empty<x-empty-state title="Aucune compagnie" />@endforelse</div><div class="mt-4">{{ $companies->links() }}</div></section>
        <section class="rounded-xl bg-white p-6 shadow-sm">
            <div class="flex flex-wrap items-center justify-between gap-3"><h2 class="font-semibold">Polices</h2><x-result-count :paginator="$policies" /></div>
            <form method="GET" class="mt-4 grid gap-3 md:grid-cols-4"><input name="q" value="{{ request('q') }}" placeholder="Véhicule ou compagnie" class="rounded border-slate-300"><select name="status" class="rounded border-slate-300"><option value="">Tous les statuts</option>@foreach($statuses as $status)<option value="{{ $status->value }}" @selected(request('status')===$status->value)>{{ $status->label() }}</option>@endforeach</select><select name="policy_type" class="rounded border-slate-300"><option value="">Tous les types</option>@foreach(['mandatory_liability','comprehensive','third_party','other'] as $type)<option value="{{ $type }}" @selected(request('policy_type')===$type)>{{ App\Support\Ui\UiLabel::get($type) }}</option>@endforeach</select><button class="rounded bg-slate-900 px-4 py-2 text-white">Filtrer</button></form>
            <div class="mt-4 overflow-x-auto"><table class="min-w-full text-sm"><thead><tr class="text-left text-slate-500"><th class="p-3">Police</th><th class="p-3">Véhicule</th><th class="p-3">Compagnie</th><th class="p-3">Échéance</th><th class="p-3">Statut</th><th class="p-3"></th></tr></thead><tbody>@forelse($policies as $policy)<tr class="border-t"><td class="p-3 font-medium">{{ $policy->maskedPolicyNumber() }}</td><td class="p-3">{{ $policy->vehicle->registration_number }}</td><td class="p-3">{{ $policy->company->name }}</td><td class="p-3">{{ App\Support\Ui\UiLabel::date($policy->ends_at) }}</td><td class="p-3"><x-status-badge :value="$policy->status" /></td><td class="p-3 text-right"><a href="{{ route('insurance.policies.show', $policy) }}" class="text-indigo-700">Ouvrir</a></td></tr>@empty<tr><td colspan="6" class="p-8"><x-empty-state title="Aucune police" description="Modifiez les filtres ou créez un brouillon." /></td></tr>@endforelse</tbody></table></div><div class="mt-4">{{ $policies->links() }}</div>
        </section>
        <section class="rounded-xl bg-white p-6 shadow-sm"><div class="flex flex-wrap items-center justify-between gap-3"><h2 class="font-semibold">Sinistres</h2><x-result-count :paginator="$claims" /></div><form method="GET" class="mt-4 grid gap-3 sm:grid-cols-3"><input name="claim_q" value="{{ request('claim_q') }}" placeholder="Numéro de sinistre" class="rounded border-slate-300"><select name="claim_status" class="rounded border-slate-300"><option value="">Tous les statuts</option>@foreach($claimStatuses as $status)<option value="{{ $status->value }}" @selected(request('claim_status')===$status->value)>{{ App\Support\Ui\UiLabel::get($status) }}</option>@endforeach</select><button class="rounded bg-slate-900 px-4 py-2 text-white">Filtrer</button></form><div class="mt-4 space-y-3 text-sm">@forelse($claims as $claim)<a href="{{ route('insurance.claims.show', $claim) }}" class="flex items-center justify-between gap-2 rounded-lg border p-4"><span><strong>{{ $claim->claim_number }}</strong> · {{ $claim->policy->maskedPolicyNumber() }}</span><x-status-badge :value="$claim->status" /></a>@empty<x-empty-state title="Aucun sinistre" />@endforelse</div><div class="mt-4">{{ $claims->links() }}</div></section>
    </div>
</x-app-layout>
