<x-app-layout><div class="rf-page">
    <x-page-header :title="__('Rentabilité par véhicule')" :eyebrow="__('Pilotage financier')" :description="__('Recettes et coûts enregistrés pour les véhicules actuellement rattachés à votre périmètre, y compris les véhicules archivés.')" />
    <x-form-errors />
    <a class="rf-button-secondary w-fit" data-no-global-loading="true" href="{{ route('vehicle-profitability.export', request()->only(['date_from', 'date_to', 'agency_id', 'currency'])) }}">{{ __('Exporter la rentabilité en CSV') }}</a>
    <x-filter-panel><form method="GET" class="grid gap-4 sm:grid-cols-2 xl:grid-cols-5" data-loading-form>
        <div><label for="profit-from" class="rf-field-label">{{ __('Du') }}</label><input id="profit-from" name="date_from" type="date" value="{{ $criteria->dateFrom() }}" class="mt-1 w-full" required></div><div><label for="profit-to" class="rf-field-label">{{ __('Au') }}</label><input id="profit-to" name="date_to" type="date" value="{{ $criteria->dateTo() }}" class="mt-1 w-full" required></div>
        <div><label for="profit-agency" class="rf-field-label">{{ __('Agence') }}</label><select id="profit-agency" name="agency_id" class="mt-1 w-full">@if(auth()->user()->agency_id === null)<option value="">{{ __('Toutes mes agences') }}</option>@endif @foreach($agencies as $agency)<option value="{{ $agency->id }}" @selected(request('agency_id', auth()->user()->agency_id) == $agency->id)>{{ $agency->name }}</option>@endforeach</select></div>
        <div><label for="profit-currency" class="rf-field-label">{{ __('Devise (facultatif)') }}</label><input id="profit-currency" name="currency" maxlength="3" pattern="[A-Za-z]{3}" value="{{ $criteria->currency }}" placeholder="MAD" class="mt-1 w-full"></div><div class="flex items-end"><x-primary-button>{{ __('Calculer') }}</x-primary-button></div>
    </form></x-filter-panel>
    <x-section-card :title="__('Comment lire ces résultats ?')"><p class="text-sm leading-6 text-slate-600">{{ __('La marge connue est le montant des factures émises non annulées moins les dépenses approuvées rattachées au véhicule, à son contrat ou à sa maintenance. Les encaissements correspondent aux allocations comptabilisées pendant la période, contrepassations déduites. Ils peuvent concerner des factures plus anciennes. Les cautions ne sont pas des recettes.') }}</p><p class="mt-2 text-sm leading-6 text-slate-600">{{ __('Chaque devise est affichée séparément. Les taxes suivent les montants enregistrés dans les factures et dépenses ; aucune déduction fiscale n’est calculée ici. Les coûts non saisis, frais généraux et amortissements ne sont pas inclus : cette marge est partielle. Les durées d’immobilisation comprennent les blocs manuels et de maintenance sur la période.') }}</p></x-section-card>
    @if($unallocated->isNotEmpty())<div role="status" class="rounded-xl border border-amber-200 bg-amber-50 p-4"><p class="font-semibold">{{ __('Dépenses sans véhicule affecté') }}</p><p class="mt-1 text-sm">{{ __('Ces dépenses de votre périmètre ne sont pas déduites des marges ci-dessous :') }}</p><ul class="mt-2">@foreach($unallocated as $entry)<li>{{ App\Support\Ui\UiLabel::money((string) $entry->amount, $entry->currency) }}</li>@endforeach</ul></div>@endif
    <div class="rf-panel overflow-x-auto"><table class="w-full text-start text-sm"><caption class="sr-only">{{ __('Recettes, dépenses et marge par véhicule et devise') }}</caption><thead class="bg-slate-50"><tr><th class="p-3">{{ __('Véhicule') }}</th><th class="p-3">{{ __('Devise') }}</th><th class="p-3">{{ __('Facturé') }}</th><th class="p-3">{{ __('Encaissé net') }}</th><th class="p-3">{{ __('Dépenses approuvées') }}</th><th class="p-3">{{ __('Marge connue') }}</th><th class="p-3">{{ __('Immobilisation') }}</th></tr></thead><tbody>
        @forelse($vehicles as $vehicle)
            @php($currencies = $amounts[$vehicle->id] ?? [])
            @forelse($currencies as $currency => $values)<tr class="border-t"><th scope="row" class="p-3">{{ $vehicle->registration_number }} @can('view', $vehicle)<a class="rf-button-link mt-1 block text-xs" href="{{ route('vehicle-economics.show', $vehicle) }}">{{ __('Coûts de possession') }}</a>@endcan<p class="font-normal text-slate-500">{{ $vehicle->brand }} {{ $vehicle->model }}</p>@if($vehicle->trashed())<span class="text-xs">{{ __('Archivé') }}</span>@endif</th><td class="p-3">{{ $currency }}</td>@foreach(['invoiced', 'collected', 'expenses', 'margin'] as $key)<td class="whitespace-nowrap p-3 {{ $key === 'margin' ? 'font-bold' : '' }}">{{ App\Support\Ui\UiLabel::money($values[$key], $currency) }}</td>@endforeach<td class="whitespace-nowrap p-3">{{ intdiv((int) ($downtime[$vehicle->id] ?? 0), 3600) }} {{ __('h') }} {{ intdiv((int) ($downtime[$vehicle->id] ?? 0) % 3600, 60) }} {{ __('min') }}</td></tr>
            @empty<tr class="border-t"><th scope="row" class="p-3">{{ $vehicle->registration_number }} @can('view', $vehicle)<a class="rf-button-link mt-1 block text-xs" href="{{ route('vehicle-economics.show', $vehicle) }}">{{ __('Coûts de possession') }}</a>@endcan</th><td colspan="5" class="p-3 text-slate-500">{{ __('Aucune écriture pour cette période et cette devise.') }}</td><td class="p-3">{{ intdiv((int) ($downtime[$vehicle->id] ?? 0), 3600) }} {{ __('h') }}</td></tr>@endforelse
        @empty<tr><td colspan="7" class="p-5"><x-empty-state :title="__('Aucun véhicule dans ce périmètre')" /></td></tr>@endforelse
    </tbody></table></div>
    <x-section-card :title="__('Résultat avec coûts estimés')" :description="__('Marge estimée = facturé − dépenses approuvées hors achat associé − amortissement − complément d’assurance − autres coûts non saisis. Les devises restent séparées.')">
        <p class="mb-4 text-sm text-slate-600">{{ __('La couverture indique le nombre de jours disposant d’hypothèses sur la période. Les estimations ne remplacent pas les factures, dépenses et encaissements présentés ci-dessus.') }}</p>
        <x-responsive-table><table class="rf-table"><thead><tr><th>{{ __('Véhicule') }}</th><th>{{ __('Amortissement estimé') }}</th><th>{{ __('Assurance non saisie') }}</th><th>{{ __('Autres coûts non saisis') }}</th><th>{{ __('Achat associé retiré des coûts') }}</th><th>{{ __('Marge économique estimée') }}</th><th>{{ __('Couverture') }}</th></tr></thead><tbody>
            @foreach($vehicles as $vehicle)
                @forelse($economics[$vehicle->id] ?? [] as $currency => $costs)<tr><th scope="row">{{ $vehicle->registration_number }}<span class="block text-xs font-normal">{{ $currency }}</span></th>@foreach(['depreciation', 'insurance_unrecorded', 'other_unrecorded', 'acquisition_recorded', 'estimated_margin'] as $key)<td class="whitespace-nowrap {{ $key === 'estimated_margin' ? 'font-bold' : '' }}">{{ App\Support\Ui\UiLabel::money($costs[$key], $currency) }}</td>@endforeach<td>{{ $costs['coverage_days'] }} {{ __('jours') }}</td></tr>
                @empty<tr><th scope="row">{{ $vehicle->registration_number }}</th><td colspan="6">{{ __('Hypothèses manquantes pour cette période et cette devise.') }} @can('view', $vehicle)<a class="rf-button-link" href="{{ route('vehicle-economics.show', $vehicle) }}">{{ __('Configurer les coûts') }}</a>@endcan</td></tr>@endforelse
            @endforeach
        </tbody></table></x-responsive-table>
    </x-section-card>
    {{ $vehicles->links() }}
</div></x-app-layout>
