<x-app-layout><div class="rf-page">
    <x-page-header title="Rentabilité par véhicule" eyebrow="Pilotage financier" description="Recettes et coûts enregistrés pour les véhicules actuellement rattachés à votre périmètre, y compris les véhicules archivés." />
    <x-form-errors />
    <a class="rf-button-secondary w-fit" data-no-global-loading="true" href="{{ route('vehicle-profitability.export', request()->only(['date_from', 'date_to', 'agency_id', 'currency'])) }}">Exporter la rentabilité en CSV</a>
    <x-filter-panel><form method="GET" class="grid gap-4 sm:grid-cols-2 xl:grid-cols-5" data-loading-form>
        <div><label for="profit-from" class="rf-field-label">Du</label><input id="profit-from" name="date_from" type="date" value="{{ $criteria->dateFrom() }}" class="mt-1 w-full" required></div><div><label for="profit-to" class="rf-field-label">Au</label><input id="profit-to" name="date_to" type="date" value="{{ $criteria->dateTo() }}" class="mt-1 w-full" required></div>
        <div><label for="profit-agency" class="rf-field-label">Agence</label><select id="profit-agency" name="agency_id" class="mt-1 w-full">@if(auth()->user()->agency_id === null)<option value="">Toutes mes agences</option>@endif @foreach($agencies as $agency)<option value="{{ $agency->id }}" @selected(request('agency_id', auth()->user()->agency_id) == $agency->id)>{{ $agency->name }}</option>@endforeach</select></div>
        <div><label for="profit-currency" class="rf-field-label">Devise (facultatif)</label><input id="profit-currency" name="currency" maxlength="3" pattern="[A-Za-z]{3}" value="{{ $criteria->currency }}" placeholder="MAD" class="mt-1 w-full"></div><div class="flex items-end"><x-primary-button>Calculer</x-primary-button></div>
    </form></x-filter-panel>
    <x-section-card title="Comment lire ces résultats ?"><p class="text-sm leading-6 text-slate-600">La marge connue est le montant des factures émises non annulées moins les dépenses approuvées rattachées au véhicule, à son contrat ou à sa maintenance. Les encaissements correspondent aux allocations comptabilisées pendant la période, contrepassations déduites. Ils peuvent concerner des factures plus anciennes. Les cautions ne sont pas des recettes.</p><p class="mt-2 text-sm leading-6 text-slate-600">Chaque devise est affichée séparément. Les taxes suivent les montants enregistrés dans les factures et dépenses ; aucune déduction fiscale n’est calculée ici. Les coûts non saisis, frais généraux et amortissements ne sont pas inclus : cette marge est partielle. Les durées d’immobilisation comprennent les blocs manuels et de maintenance sur la période.</p></x-section-card>
    @if($unallocated->isNotEmpty())<div role="status" class="rounded-xl border border-amber-200 bg-amber-50 p-4"><p class="font-semibold">Dépenses sans véhicule affecté</p><p class="mt-1 text-sm">Ces dépenses de votre périmètre ne sont pas déduites des marges ci-dessous :</p><ul class="mt-2">@foreach($unallocated as $entry)<li>{{ App\Support\Ui\UiLabel::money((string) $entry->amount, $entry->currency) }}</li>@endforeach</ul></div>@endif
    <div class="rf-panel overflow-x-auto"><table class="w-full text-left text-sm"><caption class="sr-only">Recettes, dépenses et marge par véhicule et devise</caption><thead class="bg-slate-50"><tr><th class="p-3">Véhicule</th><th class="p-3">Devise</th><th class="p-3">Facturé</th><th class="p-3">Encaissé net</th><th class="p-3">Dépenses approuvées</th><th class="p-3">Marge connue</th><th class="p-3">Immobilisation</th></tr></thead><tbody>
        @forelse($vehicles as $vehicle)
            @php($currencies = $amounts[$vehicle->id] ?? [])
            @forelse($currencies as $currency => $values)<tr class="border-t"><th scope="row" class="p-3">{{ $vehicle->registration_number }}<p class="font-normal text-slate-500">{{ $vehicle->brand }} {{ $vehicle->model }}</p>@if($vehicle->trashed())<span class="text-xs">Archivé</span>@endif</th><td class="p-3">{{ $currency }}</td>@foreach(['invoiced', 'collected', 'expenses', 'margin'] as $key)<td class="whitespace-nowrap p-3 {{ $key === 'margin' ? 'font-bold' : '' }}">{{ App\Support\Ui\UiLabel::money($values[$key], $currency) }}</td>@endforeach<td class="whitespace-nowrap p-3">{{ intdiv((int) ($downtime[$vehicle->id] ?? 0), 3600) }} h {{ intdiv((int) ($downtime[$vehicle->id] ?? 0) % 3600, 60) }} min</td></tr>
            @empty<tr class="border-t"><th scope="row" class="p-3">{{ $vehicle->registration_number }}</th><td colspan="5" class="p-3 text-slate-500">Aucune écriture pour cette période et cette devise.</td><td class="p-3">{{ intdiv((int) ($downtime[$vehicle->id] ?? 0), 3600) }} h</td></tr>@endforelse
        @empty<tr><td colspan="7" class="p-5"><x-empty-state title="Aucun véhicule dans ce périmètre" /></td></tr>@endforelse
    </tbody></table></div>
    {{ $vehicles->links() }}
</div></x-app-layout>
