@php($editing = isset($policy))
<div class="grid gap-5 md:grid-cols-2">
    @if(!$editing)<label class="text-sm">Agence<select name="agency_id" required class="mt-1 w-full rounded border-slate-300"><option value="">Choisir</option>@foreach($agencies as $agency)<option value="{{ $agency->id }}" @selected(old('agency_id') == $agency->id)>{{ $agency->name }}</option>@endforeach</select><x-input-error :messages="$errors->get('agency_id')" /></label>@else<div class="text-sm"><span class="text-slate-500">Agence immuable</span><p class="mt-1 font-medium">{{ $policy->agency?->name ?? '#'.$policy->agency_id }}</p></div>@endif
    <label class="text-sm">Véhicule<select name="vehicle_id" required class="mt-1 w-full rounded border-slate-300"><option value="">Choisir</option>@foreach($vehicles as $vehicle)<option value="{{ $vehicle->id }}" @selected(old('vehicle_id', $policy->vehicle_id ?? null) == $vehicle->id)>{{ $vehicle->registration_number }} · {{ $vehicle->brand }} {{ $vehicle->model }}</option>@endforeach</select><x-input-error :messages="$errors->get('vehicle_id')" /></label>
    <label class="text-sm">Compagnie<select name="insurance_company_id" required class="mt-1 w-full rounded border-slate-300"><option value="">Choisir</option>@foreach($companies as $company)<option value="{{ $company->id }}" @selected(old('insurance_company_id', $policy->insurance_company_id ?? null) == $company->id)>{{ $company->name }}</option>@endforeach</select><x-input-error :messages="$errors->get('insurance_company_id')" /></label>
    <label class="text-sm">Numéro de police @if(!$editing)*@endif<input name="policy_number" @required(!$editing) value="{{ old('policy_number') }}" autocomplete="off" placeholder="{{ $editing ? 'Laisser vide pour conserver le numéro' : '' }}" class="mt-1 w-full rounded border-slate-300"><x-input-error :messages="$errors->get('policy_number')" /></label>
    <label class="text-sm">Type<select name="policy_type" class="mt-1 w-full rounded border-slate-300">@foreach(['mandatory_liability'=>'Responsabilité obligatoire','comprehensive'=>'Tous risques','third_party'=>'Tiers','other'=>'Autre'] as $value => $label)<option value="{{ $value }}" @selected(old('policy_type', $policy->policy_type ?? 'mandatory_liability') === $value)>{{ $label }}</option>@endforeach</select><x-input-error :messages="$errors->get('policy_type')" /></label>
    <label class="text-sm">Début<input type="date" name="starts_at" required value="{{ old('starts_at', isset($policy) ? $policy->starts_at->toDateString() : '') }}" class="mt-1 w-full rounded border-slate-300"><x-input-error :messages="$errors->get('starts_at')" /></label>
    <label class="text-sm">Fin<input type="date" name="ends_at" required value="{{ old('ends_at', isset($policy) ? $policy->ends_at->toDateString() : '') }}" class="mt-1 w-full rounded border-slate-300"><x-input-error :messages="$errors->get('ends_at')" /></label>
    <label class="text-sm">Prime (MAD)<input name="premium_amount" inputmode="decimal" required value="{{ old('premium_amount', $policy->premium_amount ?? '0.00') }}" class="mt-1 w-full rounded border-slate-300"><x-input-error :messages="$errors->get('premium_amount')" /></label>
    <label class="text-sm">Franchise (MAD)<input name="deductible_amount" inputmode="decimal" required value="{{ old('deductible_amount', $policy->deductible_amount ?? '0.00') }}" class="mt-1 w-full rounded border-slate-300"><x-input-error :messages="$errors->get('deductible_amount')" /></label>
    <input type="hidden" name="currency" value="MAD">
</div>
