<x-app-layout>
    <div class="mx-auto max-w-5xl space-y-6">
        <div><a href="{{ route('insurance.index') }}" class="text-sm text-indigo-700">← Assurance</a><div class="mt-2 flex flex-wrap items-center justify-between gap-3"><h1 class="text-3xl font-bold">Police {{ $policy->maskedPolicyNumber() }}</h1><span class="rounded-full bg-slate-200 px-3 py-1 text-sm">{{ $policy->status }}</span></div></div>
        <section class="rounded-xl bg-white p-5 shadow-sm"><dl class="grid gap-4 text-sm md:grid-cols-3"><div><dt class="text-slate-500">Véhicule</dt><dd><a href="{{ route('vehicles.show', $policy->vehicle) }}" class="underline">{{ $policy->vehicle->registration_number }}</a></dd></div><div><dt class="text-slate-500">Compagnie</dt><dd>{{ $policy->company->name }}</dd></div><div><dt class="text-slate-500">Période</dt><dd>{{ $policy->starts_at->format('d/m/Y') }} → {{ $policy->ends_at->format('d/m/Y') }}</dd></div><div><dt class="text-slate-500">Prime</dt><dd>{{ $policy->premium_amount }} {{ $policy->currency }}</dd></div><div><dt class="text-slate-500">Franchise</dt><dd>{{ $policy->deductible_amount }} {{ $policy->currency }}</dd></div></dl></section>
        <section class="rounded-xl bg-white p-5 shadow-sm"><h2 class="font-semibold">Garanties</h2><div class="mt-4 space-y-2 text-sm">@forelse($policy->coverages as $coverage)<div class="rounded border p-3"><strong>{{ $coverage->label }}</strong> · {{ $coverage->coverage_type }} · plafond {{ $coverage->limit_amount ?? '—' }} {{ $policy->currency }} · franchise {{ $coverage->deductible_amount ?? '—' }}</div>@empty<p class="text-slate-500">Aucune garantie.</p>@endforelse</div>
            @if(auth()->user()->hasPermission('insurance.manage'))<form method="POST" action="{{ route('insurance.coverages.store', $policy) }}" class="mt-5 grid gap-3 md:grid-cols-2">@csrf<select name="coverage_type" class="rounded border-slate-300">@foreach(['liability','collision','theft','fire','glass','assistance','legal_defence','other'] as $type)<option value="{{ $type }}">{{ str_replace('_', ' ', $type) }}</option>@endforeach</select><input name="label" required value="{{ old('label') }}" placeholder="Libellé" class="rounded border-slate-300"><input name="limit_amount" inputmode="decimal" value="{{ old('limit_amount') }}" placeholder="Plafond ({{ $policy->currency }})" class="rounded border-slate-300"><input name="deductible_amount" inputmode="decimal" value="{{ old('deductible_amount') }}" placeholder="Franchise" class="rounded border-slate-300"><div><button class="rounded bg-slate-900 px-4 py-2 text-white">Ajouter la garantie</button></div></form>@endif
        </section>
        <section class="rounded-xl bg-white p-5 shadow-sm"><h2 class="font-semibold">Sinistres liés</h2><div class="mt-3 space-y-2 text-sm">@forelse($policy->claims as $claim)<a class="block underline" href="{{ route('insurance.claims.show', $claim) }}">{{ $claim->claim_number }} · {{ $claim->status->label() }}</a>@empty<p class="text-slate-500">Aucun sinistre.</p>@endforelse</div></section>
    </div>
</x-app-layout>
