<x-app-layout>
    @php($activeFilterCount = collect(['q', 'entry_type'])->filter(fn (string $key): bool => request()->filled($key))->count())
    <div class="rf-page">
        <x-page-header title="Paiements SaaS manuels" eyebrow="Administration de la plateforme" :description="'Registre administratif entre les entreprises et '.config('brand.name').', entièrement séparé des paiements de location.'"></x-page-header>
        <div class="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-950">Aucune carte, passerelle ou transaction bancaire n’est traitée ici. Ces écritures attestent uniquement une réception saisie manuellement.</div>
        <x-form-errors />
        <x-filter-panel title="Filtrer les paiements SaaS" :active-count="$activeFilterCount" :result-count="$payments->total()"><form class="rf-filter-grid" method="GET" data-loading-form><div><x-input-label for="saas-payment-search" value="Entreprise ou référence" /><input id="saas-payment-search" name="q" value="{{ request('q') }}" class="mt-1 w-full"></div><div><x-input-label for="saas-payment-type" value="Type d’écriture" /><select id="saas-payment-type" name="entry_type" class="mt-1 w-full"><option value="">Tous</option>@foreach($entryTypes as $type)<option value="{{ $type->value }}" @selected(request('entry_type') === $type->value)>{{ $type->value === 'payment' ? 'Paiement enregistré' : 'Contrepassation' }}</option>@endforeach</select></div><div class="flex items-end gap-2"><x-submit-button label="Filtrer" loading-label="Filtrage…" />@if($activeFilterCount > 0)<a href="{{ route('platform.saas-payments.index') }}" class="rf-button-secondary"><x-icon name="reset" /> Effacer</a>@endif</div></form></x-filter-panel>
        <x-responsive-table label="Registre des paiements SaaS manuels"><table><thead><tr><th>Date de réception</th><th>Entreprise</th><th>Plan</th><th>Type</th><th>Moyen</th><th>Référence</th><th class="text-right">Montant</th><th class="text-right">Action</th></tr></thead><tbody>
            @forelse($payments as $payment)<tr><td>{{ App\Support\Ui\UiLabel::dateTime($payment->occurred_at) }}</td><td>{{ $payment->tenant->name }}</td><td>{{ $payment->subscription->plan->name }}</td><td><x-status-badge :value="$payment->entry_type" /></td><td>{{ App\Support\Ui\UiLabel::get($payment->payment_method->value) }}</td><td>{{ $payment->reference ?? '—' }}</td><td class="text-right">{{ $payment->entry_type->value === 'reversal' ? '−' : '' }}{{ App\Support\Ui\UiLabel::money($payment->amount, $payment->currency) }}</td><td class="text-right">
                @if($payment->entry_type->value === 'payment' && $payment->reversal === null)<details class="inline-block text-left"><summary class="rf-button-secondary cursor-pointer"><x-icon name="warning" size="xs" />Contrepasser</summary><form method="POST" action="{{ route('platform.saas-payments.reverse', $payment) }}" class="mt-2 w-80 space-y-2 rounded-xl border bg-white p-4 shadow-xl" x-belkhir-space-confirm data-confirm-title="Contrepasser le paiement SaaS" data-confirm-resource="Paiement SaaS sélectionné" data-confirm-consequence="Une écriture de correction définitive sera créée ; le paiement d’origine restera conservé." data-confirm-label="Enregistrer la contrepassation" data-loading-form>@csrf<input type="hidden" name="idempotency_key" value="{{ (string) Illuminate\Support\Str::uuid() }}"><div><x-input-label :for="'reversal-reason-'.$payment->id" value="Motif" required /><textarea id="reversal-reason-{{ $payment->id }}" name="reason" required maxlength="2000" class="mt-1 w-full"></textarea><x-field-error :messages="$errors->get('reason')" /></div><div><x-input-label :for="'reversal-reference-'.$payment->id" value="Référence facultative" /><input id="reversal-reference-{{ $payment->id }}" name="reference" maxlength="100" class="mt-1 w-full"><x-field-error :messages="$errors->get('reference')" /></div><x-submit-button variant="danger" label="Enregistrer la contrepassation" loading-label="Enregistrement…" /></form></details>@elseif($payment->entry_type->value === 'payment')<span class="text-sm text-slate-500">Contrepassé</span>@else<span class="text-sm text-slate-500">Écriture finale</span>@endif
            </td></tr>@empty<tr><td colspan="8"><x-empty-state title="Aucun paiement SaaS manuel" description="Les registres locatifs existants restent inchangés." /></td></tr>@endforelse
        </tbody></table><x-slot:footer>{{ $payments->links() }}</x-slot:footer></x-responsive-table>
    </div>
</x-app-layout>
