<section class="rounded-xl bg-white p-5 shadow-sm">
    <div class="flex flex-wrap items-center justify-between gap-3"><div><h2 class="font-semibold">{{ __('Finance du contrat') }}</h2><p class="mt-1 text-sm text-slate-500">{{ __('Devise :') }} {{ $contract->currency }}</p></div><a href="{{ route('finance.index') }}" class="text-sm text-indigo-700 underline">{{ __('Ouvrir Finance') }}</a></div>
    <div class="mt-4 grid gap-3 text-sm md:grid-cols-4"><p class="rounded bg-slate-50 p-3">{{ __('Caution reçue') }}<br><strong>{{ App\Support\Ui\UiLabel::money($depositTotals['received'], $contract->currency) }}</strong></p><p class="rounded bg-slate-50 p-3">{{ __('Retenue') }}<br><strong>{{ App\Support\Ui\UiLabel::money($depositTotals['retained'], $contract->currency) }}</strong></p><p class="rounded bg-slate-50 p-3">{{ __('Remboursée') }}<br><strong>{{ App\Support\Ui\UiLabel::money($depositTotals['refunded'], $contract->currency) }}</strong></p><p class="rounded bg-slate-50 p-3">{{ __('Solde caution') }}<br><strong>{{ App\Support\Ui\UiLabel::money($depositTotals['balance'], $contract->currency) }}</strong></p></div>

    @if(auth()->user()->hasPermission('deposit.create') && in_array($contract->status->value, ['accepted','active','return_pending','returned']))
        <div class="mt-5 grid gap-4 lg:grid-cols-3">
            <form method="POST" action="{{ route('finance.deposits.receive', $contract) }}" class="rounded-lg border p-4">@csrf<input type="hidden" name="idempotency_key" value="web-deposit-receive-{{ Illuminate\Support\Str::uuid() }}"><label class="text-sm">{{ __('Recevoir une caution (') }}{{ $contract->currency }})<input name="amount" inputmode="decimal" required value="{{ old('amount', $contract->deposit_required) }}" class="mt-1 w-full rounded border-slate-300"><x-input-error :messages="$errors->get('amount')" /></label><button class="mt-3 rounded bg-slate-900 px-3 py-2 text-sm text-white">{{ __('Recevoir') }}</button></form>
            @if($depositTotals['balance'] !== '0.00')<form method="POST" action="{{ route('finance.deposits.retain', $contract) }}" class="rounded-lg border p-4" x-belkhir-space-confirm data-confirm-title="{{ __('Retenir une partie de la caution') }}" data-confirm-resource="{{ __('Caution du contrat sélectionné') }}" data-confirm-consequence="{{ __('La retenue définitive sera enregistrée dans l’historique financier.') }}" data-confirm-label="{{ __('Enregistrer la retenue') }}">@csrf<input type="hidden" name="idempotency_key" value="web-deposit-retain-{{ Illuminate\Support\Str::uuid() }}"><label class="text-sm">{{ __('Retenir (') }}{{ $contract->currency }})<input name="amount" inputmode="decimal" required class="mt-1 w-full rounded border-slate-300"></label><label class="mt-2 block text-sm">{{ __('Motif') }}<input name="reason" required class="mt-1 w-full rounded border-slate-300"></label><button class="mt-3 rounded border px-3 py-2 text-sm">{{ __('Retenir') }}</button></form>
            <form method="POST" action="{{ route('finance.deposits.refund', $contract) }}" class="rounded-lg border p-4" x-belkhir-space-confirm data-confirm-title="{{ __('Rembourser la caution') }}" data-confirm-resource="{{ __('Caution du contrat sélectionné') }}" data-confirm-consequence="{{ __('Le remboursement sera enregistré dans l’historique financier.') }}" data-confirm-label="{{ __('Enregistrer le remboursement') }}">@csrf<input type="hidden" name="idempotency_key" value="web-deposit-refund-{{ Illuminate\Support\Str::uuid() }}"><label class="text-sm">{{ __('Rembourser (') }}{{ $contract->currency }})<input name="amount" inputmode="decimal" required value="{{ $depositTotals['balance'] }}" class="mt-1 w-full rounded border-slate-300"></label><label class="mt-2 block text-sm">{{ __('Note') }}<input name="reason" class="mt-1 w-full rounded border-slate-300"></label><button class="mt-3 rounded border px-3 py-2 text-sm">{{ __('Rembourser') }}</button></form>@endif
        </div>
    @endif

    @if($contract->depositTransactions->isNotEmpty())
        <div class="mt-5 space-y-2 border-t pt-4 text-sm">
            <h3 class="font-medium">{{ __('Registre de caution') }}</h3>
            @foreach($contract->depositTransactions->sortByDesc('occurred_at') as $entry)
                @php($isReversed = $contract->depositTransactions->contains('reversal_of_id', $entry->id))
                <div class="flex flex-wrap items-center justify-between gap-2 rounded border p-3"><span class="flex flex-wrap items-center gap-2"><strong>{{ $entry->transaction_number }}</strong><x-status-badge :value="$entry->transaction_type" /><span>{{ App\Support\Ui\UiLabel::money($entry->amount, $entry->currency) }}</span></span>
@if(!$isReversed && $entry->transaction_type !== 'reversal' && auth()->user()->hasPermission('deposit.reverse'))<form method="POST" action="{{ route('finance.deposits.reverse', $entry) }}" class="flex min-w-0 flex-wrap gap-2" x-belkhir-space-confirm data-confirm-title="{{ __('Contrepasser le mouvement') }}" data-confirm-resource="{{ __('Mouvement de caution sélectionné') }}" data-confirm-consequence="{{ __('Une écriture de correction définitive sera créée ; l’écriture d’origine restera conservée.') }}" data-confirm-label="{{ __('Contrepasser') }}">@csrf<input type="hidden" name="idempotency_key" value="web-deposit-reverse-{{ Illuminate\Support\Str::uuid() }}"><label class="sr-only" for="deposit-reversal-reason-{{ $entry->id }}">{{ __('Motif de la contrepassation') }}</label><input id="deposit-reversal-reason-{{ $entry->id }}" name="reason" required placeholder="{{ __('Motif') }}" class="min-w-0 flex-1 rounded border-slate-300"><button class="min-h-10 text-red-700 underline">{{ __('Contrepasser') }}</button></form>@elseif($isReversed)<span class="text-xs text-slate-500">{{ __('Contrepassé') }}</span>@endif
                </div>
            @endforeach
        </div>
    @endif

    <div class="mt-5 border-t pt-5">
        @if($contract->invoice)<p class="flex flex-wrap items-center gap-2 text-sm">{{ __('Facture :') }} <a class="font-medium text-brand-700 underline" href="{{ route('finance.invoices.show', $contract->invoice) }}">{{ $contract->invoice->invoice_number }}</a><x-status-badge :value="$contract->invoice->status" /> {{ __('solde') }} {{ App\Support\Ui\UiLabel::money($contract->invoice->balance_due, $contract->invoice->currency) }}</p>
        @elseif($contract->status->value === 'returned' && auth()->user()->hasPermission('invoice.create'))<form method="POST" action="{{ route('finance.invoices.create', $contract) }}" class="flex flex-wrap gap-2">@csrf<select name="tax_mode" class="rounded border-slate-300"><option value="none">{{ __('Sans taxe officielle') }}</option><option value="inclusive">{{ __('Taxe incluse') }}</option><option value="exclusive">{{ __('Taxe ajoutée') }}</option></select><input name="tax_rate" inputmode="decimal" value="0.0000" class="w-32 rounded border-slate-300"><button class="inline-flex items-center gap-2 rounded bg-slate-900 px-4 py-2 text-white"><x-icon name="add" size="xs" />{{ __('Créer la facture') }}</button></form>
        @else<p class="text-sm text-slate-500">{{ __('La facture devient disponible après finalisation du retour et revue de tous les frais.') }}</p>@endif
    </div>
    @if($contract->status->value === 'returned' && auth()->user()->hasPermission('contract.close'))<form method="POST" action="{{ route('finance.contracts.close', $contract) }}" class="mt-4" x-belkhir-space-confirm data-confirm-title="{{ __('Clôturer le contrat') }}" data-confirm-resource="{{ __('Contrat de location sélectionné') }}" data-confirm-consequence="{{ __('La clôture financière sera appliquée uniquement si la facture, les paiements et la caution satisfont les règles existantes.') }}" data-confirm-label="{{ __('Vérifier et clôturer') }}">@csrf<button class="rounded bg-slate-900 px-4 py-2 text-white">{{ __('Vérifier et clôturer') }}</button><p class="mt-1 text-xs text-slate-500">{{ __('Exige une facture payée, aucun paiement en attente et une caution soldée.') }}</p></form>@endif
</section>
