<x-app-layout>
    <div class="space-y-8">
        <div><p class="text-sm text-slate-500">Flotte</p><h1 class="text-3xl font-bold">Maintenance</h1><p class="mt-2 text-sm text-slate-600">L’approbation crée un bloc d’indisponibilité protégé par PostgreSQL.</p></div>
        @if(auth()->user()->hasPermission('maintenance.create'))<form method="POST" action="{{ route('maintenance.store') }}" class="grid gap-4 rounded-xl bg-white p-6 shadow-sm md:grid-cols-3">@csrf
            <select name="agency_id" required class="rounded-lg border-slate-300"><option value="">Agence</option>@foreach($vehicles->unique('agency_id') as $vehicle)<option value="{{ $vehicle->agency_id }}">Agence #{{ $vehicle->agency_id }}</option>@endforeach</select>
            <select name="vehicle_id" required class="rounded-lg border-slate-300"><option value="">Véhicule</option>@foreach($vehicles as $vehicle)<option value="{{ $vehicle->id }}">{{ $vehicle->registration_number }} · {{ $vehicle->brand }} {{ $vehicle->model }}</option>@endforeach</select>
            <input name="title" required placeholder="Objet" class="rounded-lg border-slate-300"><select name="maintenance_type" class="rounded-lg border-slate-300"><option value="preventive">Préventive</option><option value="corrective">Corrective</option><option value="inspection">Inspection</option><option value="repair">Réparation</option></select><select name="priority" class="rounded-lg border-slate-300"><option value="normal">Normale</option><option value="high">Haute</option><option value="critical">Critique</option><option value="low">Basse</option></select><input name="estimated_cost" value="0.00" class="rounded-lg border-slate-300"><input type="datetime-local" name="scheduled_start_at" class="rounded-lg border-slate-300"><input type="datetime-local" name="scheduled_end_at" class="rounded-lg border-slate-300"><button class="rounded-lg bg-slate-900 px-4 py-2 text-white">Planifier</button>
        </form>@endif
        <section class="rounded-xl bg-white p-6 shadow-sm"><div class="overflow-x-auto"><table class="min-w-full text-sm"><thead><tr class="text-left text-slate-500"><th class="py-2">Ordre</th><th>Véhicule</th><th>Objet</th><th>Période</th><th>Statut</th><th>Actions</th></tr></thead><tbody>@forelse($orders as $order)<tr class="border-t"><td class="py-3">{{ $order->maintenance_number }}</td><td>{{ $order->vehicle->registration_number }}</td><td>{{ $order->title }}</td><td>{{ $order->scheduled_start_at?->format('d/m H:i') }} → {{ $order->scheduled_end_at?->format('d/m H:i') }}</td><td>{{ $order->status }}</td><td class="flex gap-2 py-2">@if($order->status === 'planned' && auth()->user()->hasPermission('maintenance.approve'))<form method="POST" action="{{ route('maintenance.approve', $order) }}">@csrf<button class="text-indigo-700">Approuver</button></form>@endif @if($order->status === 'approved' && auth()->user()->hasPermission('maintenance.start'))<form method="POST" action="{{ route('maintenance.start', $order) }}">@csrf<button class="text-indigo-700">Démarrer</button></form>@endif</td></tr>@empty<tr><td colspan="6" class="py-8 text-slate-500">Aucune maintenance.</td></tr>@endforelse</tbody></table></div>{{ $orders->links() }}</section>
    </div>
</x-app-layout>
