<x-app-layout>
    <div class="space-y-6">
        <x-page-header :title="__('Maintenance')" :eyebrow="__('Flotte')" :description="__('L’approbation crée un bloc d’indisponibilité protégé par PostgreSQL.')">
            <x-slot:actions>@if(auth()->user()->hasPermission('maintenance.create'))<a href="{{ route('maintenance.create') }}" class="rounded-lg bg-slate-900 px-4 py-2 text-sm text-white">{{ __('Nouvel ordre') }}</a>@endif</x-slot:actions>
        </x-page-header>
        <div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-5">@foreach($summary as $label => $value)<x-stat-card :label="$label" :value="$value" />@endforeach</div>
        <form method="GET" class="grid gap-3 rounded-xl bg-white p-4 sm:grid-cols-3"><input name="q" value="{{ request('q') }}" placeholder="{{ __('Numéro ou objet') }}" aria-label="{{ __('Recherche') }}"><select name="status" aria-label="{{ __('Statut') }}"><option value="">{{ __('Tous les statuts') }}</option>@foreach($statuses as $status)<option value="{{ $status }}" @selected(request('status') === $status)>{{ App\Support\Ui\UiLabel::get($status) }}</option>@endforeach</select><button type="submit" class="inline-flex items-center justify-center gap-2 rounded-lg bg-slate-900 px-4 py-2 text-white"><x-icon name="filter" size="xs" />{{ __('Filtrer') }}</button></form>
        <x-result-count :paginator="$orders" />
        <x-responsive-table :label="__('Ordres de maintenance')"><table><thead><tr><th>{{ __('Ordre') }}</th><th>{{ __('Véhicule') }}</th><th>{{ __('Objet') }}</th><th>{{ __('Période') }}</th><th>{{ __('Statut') }}</th><th><span class="sr-only">{{ __('Actions') }}</span></th></tr></thead><tbody>@forelse($orders as $order)<tr><td class="font-medium">{{ $order->maintenance_number }}</td><td>{{ $order->vehicle->registration_number }}</td><td>{{ $order->title }}</td><td>{{ App\Support\Ui\UiLabel::dateTime($order->scheduled_start_at) }} → {{ App\Support\Ui\UiLabel::dateTime($order->scheduled_end_at) }}</td><td><x-status-badge :value="$order->status" /></td><td class="text-end"><x-icon-button icon="view" :label="__('Consulter l’ordre de maintenance')" :href="route('maintenance.show', $order)" /></td></tr>@empty<tr><td colspan="6" class="p-10 text-center text-slate-500">{{ __('Aucun ordre de maintenance ne correspond aux filtres.') }}</td></tr>@endforelse</tbody></table></x-responsive-table>{{ $orders->links() }}
    </div>
</x-app-layout>
