<x-app-layout>
    <div class="space-y-6">
        <x-page-header title="Maintenance" eyebrow="Flotte" description="L’approbation crée un bloc d’indisponibilité protégé par PostgreSQL.">
            <x-slot:actions>@if(auth()->user()->hasPermission('maintenance.create'))<a href="{{ route('maintenance.create') }}" class="rounded-lg bg-slate-900 px-4 py-2 text-sm text-white">Nouvel ordre</a>@endif</x-slot:actions>
        </x-page-header>
        <form method="GET" class="grid gap-3 rounded-xl bg-white p-4 sm:grid-cols-3"><input name="q" value="{{ request('q') }}" placeholder="Numéro ou objet" aria-label="Recherche"><select name="status" aria-label="Statut"><option value="">Tous les statuts</option>@foreach($statuses as $status)<option value="{{ $status }}" @selected(request('status') === $status)>{{ App\Support\Ui\UiLabel::get($status) }}</option>@endforeach</select><button type="submit" class="rounded-lg bg-slate-900 px-4 py-2 text-white">Filtrer</button></form>
        <x-result-count :paginator="$orders" />
        <section class="overflow-x-auto rounded-xl bg-white shadow-sm"><table class="min-w-full text-sm"><thead><tr class="text-left text-slate-500"><th class="p-4">Ordre</th><th class="p-4">Véhicule</th><th class="p-4">Objet</th><th class="p-4">Période</th><th class="p-4">Statut</th><th class="p-4"><span class="sr-only">Actions</span></th></tr></thead><tbody>@forelse($orders as $order)<tr class="border-t"><td class="p-4 font-medium">{{ $order->maintenance_number }}</td><td class="p-4">{{ $order->vehicle->registration_number }}</td><td class="p-4">{{ $order->title }}</td><td class="p-4">{{ App\Support\Ui\UiLabel::dateTime($order->scheduled_start_at) }} → {{ App\Support\Ui\UiLabel::dateTime($order->scheduled_end_at) }}</td><td class="p-4"><x-status-badge :value="$order->status" /></td><td class="p-4 text-right"><a href="{{ route('maintenance.show', $order) }}" class="text-indigo-700">Ouvrir</a></td></tr>@empty<tr><td colspan="6" class="p-10 text-center text-slate-500">Aucun ordre de maintenance ne correspond aux filtres.</td></tr>@endforelse</tbody></table></section>{{ $orders->links() }}
    </div>
</x-app-layout>
