<x-app-layout>
    <div class="mx-auto max-w-6xl space-y-6">
        <div class="flex flex-wrap items-center justify-between gap-3"><div><p class="text-sm text-slate-500">{{ $reservation->status->label() }}</p><h1 class="text-2xl font-bold">{{ $reservation->reservation_number }}</h1></div><div class="flex gap-2">@can('update', $reservation)<a href="{{ route('reservations.edit', $reservation) }}" class="rounded-lg border bg-white px-4 py-2 text-sm">Modifier</a>@endcan @can('confirm', $reservation)<form method="POST" action="{{ route('reservations.confirm', $reservation) }}">@csrf<button class="rounded-lg bg-emerald-700 px-4 py-2 text-sm text-white">Confirmer et bloquer</button></form>@endcan</div></div>
        @if($reservation->rentalContract)<div><a href="{{ route('contracts.show', $reservation->rentalContract) }}" class="inline-flex rounded-lg bg-slate-900 px-4 py-2 text-sm text-white">Voir le contrat</a></div>@elseif($reservation->status->value === 'confirmed')@can('create', App\Models\RentalContract::class)<form method="POST" action="{{ route('contracts.store', $reservation) }}">@csrf<button class="rounded-lg bg-slate-900 px-4 py-2 text-sm text-white">Créer le contrat depuis cette réservation</button></form>@endcan @endif
        @if($errors->any())<div class="rounded-lg bg-red-50 p-4 text-sm text-red-800">{{ $errors->first() }}</div>@endif
        <div class="grid gap-6 lg:grid-cols-2"><section class="rounded-xl bg-white p-5 shadow-sm"><h2 class="font-semibold">Détails</h2><dl class="mt-4 grid grid-cols-2 gap-3 text-sm"><dt class="text-slate-500">Agence</dt><dd>{{ $reservation->agency->name }}</dd><dt class="text-slate-500">Client</dt><dd>{{ $reservation->customer->displayName() }}</dd><dt class="text-slate-500">Conducteur</dt><dd>{{ $reservation->driver ? $reservation->driver->first_name.' '.$reservation->driver->last_name : 'Non sélectionné' }}</dd><dt class="text-slate-500">Catégorie</dt><dd>{{ $reservation->vehicleCategory->name }}</dd><dt class="text-slate-500">Véhicule</dt><dd>{{ $reservation->vehicle?->registration_number ?? 'Non affecté' }}</dd><dt class="text-slate-500">Début</dt><dd>{{ $reservation->starts_at->timezone(config('reservations.display_timezone'))->format('d/m/Y H:i') }}</dd><dt class="text-slate-500">Fin</dt><dd>{{ $reservation->ends_at->timezone(config('reservations.display_timezone'))->format('d/m/Y H:i') }}</dd></dl></section>
            <section class="rounded-xl bg-white p-5 shadow-sm"><h2 class="font-semibold">Tarification</h2>@if($reservation->status->canBeConfirmed())@if($quote)<dl class="mt-4 grid grid-cols-2 gap-3 text-sm"><dt>Jours facturés</dt><dd>{{ $quote['billed_days'] }}</dd><dt>Tarif journalier</dt><dd>{{ $quote['daily_rate'] }} {{ $quote['currency'] }}</dd><dt>Sous-total</dt><dd>{{ $quote['subtotal'] }} {{ $quote['currency'] }}</dd><dt class="font-semibold">Total location</dt><dd class="font-semibold">{{ $quote['total_amount'] }} {{ $quote['currency'] }}</dd><dt>Caution séparée</dt><dd>{{ $quote['deposit_amount'] }} {{ $quote['currency'] }}</dd></dl><p class="mt-3 text-xs text-amber-700">Aperçu : le snapshot sera figé à la confirmation.</p>@else<p class="mt-4 text-sm text-amber-700">{{ $quoteError }}</p>@endif @else<dl class="mt-4 grid grid-cols-2 gap-3 text-sm"><dt>Jours facturés</dt><dd>{{ $reservation->billed_days }}</dd><dt>Tarif journalier</dt><dd>{{ $reservation->daily_rate }} {{ $reservation->currency }}</dd><dt>Total location</dt><dd class="font-semibold">{{ $reservation->total_amount }} {{ $reservation->currency }}</dd><dt>Caution séparée</dt><dd>{{ $reservation->deposit_amount }} {{ $reservation->currency }}</dd></dl><details class="mt-4 text-xs"><summary class="cursor-pointer text-slate-600">Snapshot tarifaire figé</summary><pre class="mt-2 overflow-auto rounded bg-slate-100 p-3">{{ json_encode($reservation->pricing_snapshot, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE) }}</pre></details>@endif</section></div>
        <div class="grid gap-6 lg:grid-cols-2"><section class="rounded-xl bg-white p-5 shadow-sm"><h2 class="font-semibold">Historique des statuts</h2><ol class="mt-4 space-y-3 text-sm">@foreach($reservation->statusHistories->sortByDesc('created_at') as $history)<li class="border-l-2 border-slate-300 pl-3"><span class="font-medium">{{ $history->to_status->label() }}</span><br><span class="text-slate-500">{{ $history->created_at->timezone(config('reservations.display_timezone'))->format('d/m/Y H:i') }}{{ $history->reason ? ' — '.$history->reason : '' }}</span></li>@endforeach</ol></section><section class="rounded-xl bg-white p-5 shadow-sm"><h2 class="font-semibold">Disponibilité</h2>@php($activeBlock = $reservation->vehicleBlocks->firstWhere('status.value', 'active'))<p class="mt-4 text-sm {{ $activeBlock ? 'text-red-700' : 'text-slate-500' }}">{{ $activeBlock ? 'Bloc actif : ce véhicule est indisponible sur la période.' : 'Aucun bloc actif pour cette réservation.' }}</p>@can('cancel', $reservation)<form method="POST" action="{{ route('reservations.cancel', $reservation) }}" class="mt-6 space-y-2">@csrf<label class="text-sm">Motif d’annulation<textarea name="reason" required rows="2" class="mt-1 w-full rounded-lg border-slate-300"></textarea></label><button class="rounded-lg bg-red-700 px-4 py-2 text-sm text-white">Annuler la réservation</button></form>@endcan</section></div>
    </div>
</x-app-layout>
