<x-app-layout>
    <div class="rf-page max-w-4xl">
        <x-page-header :title="$tenant->exists ? __('Modifier l’entreprise cliente') : __('Créer une entreprise cliente')" :eyebrow="__('Administration de la plateforme')" :breadcrumbs="[['label' => __('Entreprises clientes'), 'url' => route('platform.tenants.index')], ['label' => $tenant->exists ? $tenant->name : __('Nouvelle entreprise')]]" />
        <form method="POST" action="{{ $tenant->exists ? route('platform.tenants.update', $tenant) : route('platform.tenants.store') }}" class="rf-panel space-y-6 p-6">@csrf @if($tenant->exists)@method('PUT')@endif
            <section><h2 class="font-semibold">{{ __('Entreprise') }}</h2><div class="mt-4 grid gap-4 md:grid-cols-2"><label class="text-sm">{{ __('Nom') }}<input name="name" required value="{{ old('name', $tenant->name) }}" class="mt-1 w-full rounded border-slate-300"></label><label class="text-sm">{{ __('Identifiant technique') }}<input name="slug" required value="{{ old('slug', $tenant->slug) }}" class="mt-1 w-full rounded border-slate-300"></label><label class="text-sm">{{ __('Raison sociale') }}<input name="legal_name" value="{{ old('legal_name', $tenant->legal_name) }}" class="mt-1 w-full rounded border-slate-300"></label><label class="text-sm">{{ __('E-mail') }}<input type="email" name="email" value="{{ old('email', $tenant->email) }}" class="mt-1 w-full rounded border-slate-300"></label><label class="text-sm">{{ __('Téléphone') }}<input name="phone" value="{{ old('phone', $tenant->phone) }}" class="mt-1 w-full rounded border-slate-300"></label><label class="text-sm md:col-span-2">{{ __('Adresse') }}<textarea name="address" class="mt-1 w-full rounded border-slate-300">{{ old('address', $tenant->settings['address'] ?? '') }}</textarea></label><label class="text-sm">{{ __('Devise') }}<input name="currency" required value="{{ old('currency', $tenant->settings['currency'] ?? 'MAD') }}" maxlength="3" class="mt-1 w-full rounded border-slate-300"></label><label class="text-sm">{{ __('Fuseau horaire') }}<input name="timezone" required value="{{ old('timezone', $tenant->settings['timezone'] ?? 'Africa/Casablanca') }}" class="mt-1 w-full rounded border-slate-300"></label></div></section>
            @unless($tenant->exists)<section class="border-t pt-6"><h2 class="font-semibold">{{ __('Agence initiale') }}</h2><div class="mt-4 grid gap-4 md:grid-cols-2"><label class="text-sm">{{ __('Code') }}<input name="agency_code" required value="{{ old('agency_code') }}" class="mt-1 w-full rounded border-slate-300"></label><label class="text-sm">{{ __('Nom') }}<input name="agency_name" required value="{{ old('agency_name') }}" class="mt-1 w-full rounded border-slate-300"></label><label class="text-sm">{{ __('E-mail') }}<input type="email" name="agency_email" value="{{ old('agency_email') }}" class="mt-1 w-full rounded border-slate-300"></label><label class="text-sm">{{ __('Téléphone') }}<input name="agency_phone" value="{{ old('agency_phone') }}" class="mt-1 w-full rounded border-slate-300"></label><label class="text-sm md:col-span-2">{{ __('Adresse') }}<textarea name="agency_address" class="mt-1 w-full rounded border-slate-300">{{ old('agency_address') }}</textarea></label></div></section><section class="border-t pt-6"><h2 class="font-semibold">{{ __('Administrateur initial de l’entreprise') }}</h2><div class="mt-4 grid gap-4 md:grid-cols-2"><label class="text-sm">{{ __('Nom') }}<input name="owner_name" required value="{{ old('owner_name') }}" class="mt-1 w-full rounded border-slate-300"></label><label class="text-sm">{{ __('E-mail de connexion') }}<input type="email" name="owner_email" required value="{{ old('owner_email') }}" class="mt-1 w-full rounded border-slate-300"></label></div><p class="mt-3 text-sm text-slate-500">{{ __('Un mot de passe temporaire aléatoire sera affiché une seule fois après création.') }}</p></section>@endunless
            <x-form-errors /><div class="flex justify-end gap-3"><a href="{{ $tenant->exists ? route('platform.tenants.show', $tenant) : route('platform.tenants.index') }}" class="rf-button-secondary"><x-icon name="previous" size="xs" />{{ __('Annuler') }}</a><button class="rf-button-primary"><x-icon :name="$tenant->exists ? 'save' : 'add'" size="xs" />{{ $tenant->exists ? __('Enregistrer') : __('Créer l’entreprise') }}</button></div>
        </form>
    </div>
</x-app-layout>
