<x-app-layout>
    <div class="mx-auto max-w-4xl space-y-6"><div><p class="text-sm text-slate-500">Administration SaaS</p><h1 class="text-3xl font-bold">{{ $tenant->exists ? 'Modifier le tenant' : 'Provisionner un tenant' }}</h1></div>
        <form method="POST" action="{{ $tenant->exists ? route('platform.tenants.update', $tenant) : route('platform.tenants.store') }}" class="space-y-6 rounded-xl bg-white p-6 shadow-sm">@csrf @if($tenant->exists)@method('PUT')@endif
            <section><h2 class="font-semibold">Entreprise</h2><div class="mt-4 grid gap-4 md:grid-cols-2"><label class="text-sm">Nom<input name="name" required value="{{ old('name', $tenant->name) }}" class="mt-1 w-full rounded border-slate-300"></label><label class="text-sm">Slug<input name="slug" required value="{{ old('slug', $tenant->slug) }}" class="mt-1 w-full rounded border-slate-300"></label><label class="text-sm">Raison sociale<input name="legal_name" value="{{ old('legal_name', $tenant->legal_name) }}" class="mt-1 w-full rounded border-slate-300"></label><label class="text-sm">E-mail<input type="email" name="email" value="{{ old('email', $tenant->email) }}" class="mt-1 w-full rounded border-slate-300"></label><label class="text-sm">Téléphone<input name="phone" value="{{ old('phone', $tenant->phone) }}" class="mt-1 w-full rounded border-slate-300"></label><label class="text-sm md:col-span-2">Adresse<textarea name="address" class="mt-1 w-full rounded border-slate-300">{{ old('address', $tenant->settings['address'] ?? '') }}</textarea></label><label class="text-sm">Devise<input name="currency" required value="{{ old('currency', $tenant->settings['currency'] ?? 'MAD') }}" maxlength="3" class="mt-1 w-full rounded border-slate-300"></label><label class="text-sm">Timezone<input name="timezone" required value="{{ old('timezone', $tenant->settings['timezone'] ?? 'Africa/Casablanca') }}" class="mt-1 w-full rounded border-slate-300"></label></div></section>
            @unless($tenant->exists)<section class="border-t pt-6"><h2 class="font-semibold">Agence initiale</h2><div class="mt-4 grid gap-4 md:grid-cols-2"><label class="text-sm">Code<input name="agency_code" required value="{{ old('agency_code') }}" class="mt-1 w-full rounded border-slate-300"></label><label class="text-sm">Nom<input name="agency_name" required value="{{ old('agency_name') }}" class="mt-1 w-full rounded border-slate-300"></label><label class="text-sm">E-mail<input type="email" name="agency_email" value="{{ old('agency_email') }}" class="mt-1 w-full rounded border-slate-300"></label><label class="text-sm">Téléphone<input name="agency_phone" value="{{ old('agency_phone') }}" class="mt-1 w-full rounded border-slate-300"></label><label class="text-sm md:col-span-2">Adresse<textarea name="agency_address" class="mt-1 w-full rounded border-slate-300">{{ old('agency_address') }}</textarea></label></div></section><section class="border-t pt-6"><h2 class="font-semibold">Tenant Owner initial</h2><div class="mt-4 grid gap-4 md:grid-cols-2"><label class="text-sm">Nom<input name="owner_name" required value="{{ old('owner_name') }}" class="mt-1 w-full rounded border-slate-300"></label><label class="text-sm">E-mail de connexion<input type="email" name="owner_email" required value="{{ old('owner_email') }}" class="mt-1 w-full rounded border-slate-300"></label></div><p class="mt-3 text-sm text-slate-500">Un mot de passe temporaire aléatoire sera affiché une seule fois après création.</p></section>@endunless
            @if($errors->any())<div class="rounded-lg bg-red-50 p-3 text-sm text-red-800">{{ $errors->first() }}</div>@endif<div class="flex justify-end gap-3"><a href="{{ $tenant->exists ? route('platform.tenants.show', $tenant) : route('platform.tenants.index') }}" class="rounded border px-4 py-2">Annuler</a><button class="rounded bg-slate-950 px-5 py-2 text-white">{{ $tenant->exists ? 'Enregistrer' : 'Provisionner atomiquement' }}</button></div>
        </form>
    </div>
</x-app-layout>
