<x-portal-layout>
    <p class="text-slate-600">Bienvenue {{ $customer->displayName() }}. Cet espace concerne uniquement vos dossiers auprès de cette agence.</p>
    <x-section-card title="Mes réservations">
        <div class="grid gap-4 md:grid-cols-2">@forelse($reservations as $reservation)<article class="rounded-xl border p-4"><div class="flex flex-wrap justify-between gap-2"><h2 class="font-semibold">{{ $reservation->reservation_number }}</h2><x-status-badge :value="$reservation->status" /></div><p class="mt-2">{{ $reservation->vehicle?->brand }} {{ $reservation->vehicle?->model }}</p><p class="mt-1 text-sm text-slate-600">{{ App\Support\Ui\UiLabel::dateTime($reservation->starts_at) }} → {{ App\Support\Ui\UiLabel::dateTime($reservation->ends_at) }}</p></article>@empty<x-empty-state title="Aucune réservation confirmée" />@endforelse</div><div class="mt-4">{{ $reservations->withQueryString()->links() }}</div>
    </x-section-card>
    <div class="grid gap-6 lg:grid-cols-2">
        <x-section-card title="Mes contrats"><ul class="divide-y">@forelse($contracts as $contract)<li class="py-3"><p class="font-semibold">{{ $contract->contract_number }}</p><x-status-badge :value="$contract->status" />@if($contract->currentVersion?->locked_at && $contract->currentVersion?->document_id)<a class="rf-button-link mt-2 block" data-no-global-loading="true" href="{{ route('portal.contract', $contract->id) }}">Télécharger le contrat</a>@else<p class="mt-2 text-sm text-slate-500">Votre agence prépare le document.</p>@endif</li>@empty<li><x-empty-state title="Aucun contrat accepté" /></li>@endforelse</ul>{{ $contracts->withQueryString()->links() }}</x-section-card>
        <x-section-card title="Mes factures"><ul class="divide-y">@forelse($invoices as $invoice)<li class="py-3"><p class="font-semibold">{{ $invoice->invoice_number }}</p><p class="mt-1">{{ App\Support\Ui\UiLabel::money($invoice->total_amount, $invoice->currency) }}</p><p class="mt-1 text-sm text-slate-600">Reste à régler : {{ App\Support\Ui\UiLabel::money($invoice->balance_due, $invoice->currency) }}</p><a class="rf-button-link mt-2 inline-flex" href="{{ route('portal.invoice', $invoice->id) }}">Consulter / enregistrer en PDF</a></li>@empty<li><x-empty-state title="Aucune facture émise" /></li>@endforelse</ul>{{ $invoices->withQueryString()->links() }}</x-section-card>
    </div>
    <x-section-card title="Transmettre un justificatif" description="PDF, JPG, PNG ou WebP, 5 Mo maximum. L’agence vérifiera les documents transmis.">
        <form method="POST" enctype="multipart/form-data" action="{{ route('portal.upload') }}" class="grid gap-4 sm:grid-cols-2" data-loading-form>@csrf
            <div><label for="portal-type" class="rf-field-label">Type de document</label><select id="portal-type" name="document_type" class="mt-1 w-full"><option value="customer_identity">Pièce d’identité</option><option value="other">Autre justificatif</option></select><x-field-error :messages="$errors->get('document_type')" /></div>
            <div><label for="portal-file" class="rf-field-label">Fichier</label><input id="portal-file" type="file" name="file" accept=".pdf,.jpg,.jpeg,.png,.webp" required class="mt-1 w-full"><x-field-error :messages="$errors->get('file')" /></div><div><x-primary-button>Transmettre à l’agence</x-primary-button></div>
        </form>
        <ul class="mt-5 divide-y">@foreach($uploads as $document)<li class="flex flex-wrap items-center justify-between gap-2 py-3 text-sm"><span>{{ $document->title }} · {{ App\Support\Ui\UiLabel::date($document->created_at) }}</span><a class="rf-button-link" data-no-global-loading="true" href="{{ route('portal.document', $document->id) }}">Télécharger mon envoi</a></li>@endforeach</ul>
    </x-section-card>
</x-portal-layout>
